/* ------------------------------------------------------------ */
/* TITLE:		 Find Inpatient Stays initiated by physician    */
/* 				 referral, clinic referral, or HMO referral  	*/
/* AUTHOR:		 Ian McCarthy									*/
/* 				 Emory University								*/
/* DATE CREATED: 2/20/2017										*/
/* DATE EDITED:  2/28/2024										*/
/* CODE FILE ORDER: 1 of XX  									*/
/* NOTES:														*/
/*   -- File outputs the following tables to PL027710:			*/
/*		InpatientStays_2007-2015  								*/
/* ------------------------------------------------------------ */

/* Create Table of Inpatient (Hospital Only) Stays for 2007 */
DATA WORK.InpatientStays_2007;
	SET	RIF2007.INPATIENT_CLAIMS_01
  		RIF2007.INPATIENT_CLAIMS_02
		RIF2007.INPATIENT_CLAIMS_03
		RIF2007.INPATIENT_CLAIMS_04
		RIF2007.INPATIENT_CLAIMS_05
		RIF2007.INPATIENT_CLAIMS_06
		RIF2007.INPATIENT_CLAIMS_07
		RIF2007.INPATIENT_CLAIMS_08
		RIF2007.INPATIENT_CLAIMS_09
		RIF2007.INPATIENT_CLAIMS_10
		RIF2007.INPATIENT_CLAIMS_11
		RIF2007.INPATIENT_CLAIMS_12;
RUN;

PROC SQL;
	DROP TABLE PL027710.InpatientStays_2007;
	CREATE TABLE PL027710.InpatientStays_2007 AS
	SELECT a.BENE_ID, a.CLM_ID, a.CLM_ADMSN_DT, a.NCH_BENE_DSCHRG_DT, a.CLM_FROM_DT, a.CLM_THRU_DT, a.PRVDR_NUM, 
		CASE
			WHEN a.ORG_NPI_NUM NE '' AND a.ORG_NPI_NUM NE '0000000000' THEN a.ORG_NPI_NUM
			WHEN a.ORG_NPI_NUM='' OR a.ORG_NPI_NUM='0000000000' THEN b.NPI
		ELSE ''
		END AS ORG_NPI_NUM,
		a.OP_PHYSN_UPIN,
		CASE 
			WHEN a.OP_PHYSN_NPI NE '' AND a.OP_PHYSN_NPI NE '0000000000' THEN a.OP_PHYSN_NPI
			WHEN a.OP_PHYSN_NPI='' OR a.OP_PHYSN_NPI='0000000000' THEN c.NPI
		ELSE ''
		END AS OP_PHYSN_NPI,
		a.CLM_DRG_CD, a.ADMTG_DGNS_CD, a.ICD_DGNS_CD1, a.PRNCPAL_DGNS_CD, a.ICD_PRCDR_CD1, 
		a.CLM_PMT_AMT, a.CLM_TOT_CHRG_AMT, a.NCH_PRMRY_PYR_CLM_PD_AMT, a.NCH_IP_TOT_DDCTN_AMT,
		a.CLM_PMT_AMT + a.NCH_PRMRY_PYR_CLM_PD_AMT + a.NCH_IP_TOT_DDCTN_AMT AS Inpatient_Spend,
		a.ICD_DGNS_CD2, a.ICD_DGNS_CD3, a.ICD_DGNS_CD4, a.ICD_DGNS_CD5, a.ICD_DGNS_CD6, a.ICD_DGNS_CD7,
		a.ICD_DGNS_CD8, a.ICD_DGNS_CD9, a.ICD_DGNS_CD10, d.drgweight,
		a.ICD_PRCDR_CD2, a.ICD_PRCDR_CD3, a.ICD_PRCDR_CD4, a.ICD_PRCDR_CD5,
		a.ICD_PRCDR_CD6, a.ICD_PRCDR_CD7, a.ICD_PRCDR_CD8, a.ICD_PRCDR_CD9, a.ICD_PRCDR_CD10,
		a.PTNT_DSCHRG_STUS_CD AS DCHRG_STS
	FROM WORK.InpatientStays_2007 AS a
	LEFT JOIN PL027710.PRVN_NPI_Merge_2007 AS b
		ON a.PRVDR_NUM=b.PRVDR_NUM
	LEFT JOIN PL027710.UPIN_NPI_Merge_2007 AS c
		ON a.OP_PHYSN_UPIN=c.OP_PHYSN_UPIN
	LEFT JOIN (SELECT * FROM PL027710.DRG_Weights WHERE fyear=2007) AS d
		ON input(a.CLM_DRG_CD,18.)=d.drg
	WHERE CLM_SRC_IP_ADMSN_CD IN ("1","2","3")
		  AND (NCH_CLM_TYPE_CD="60")
		  AND (CLM_IP_ADMSN_TYPE_CD="3");
QUIT;


/* Create Table of Inpatient (Hospital Only) Stays for 2008 */
DATA WORK.InpatientStays_2008;
	SET	RIF2008.INPATIENT_CLAIMS_01
  		RIF2008.INPATIENT_CLAIMS_02
		RIF2008.INPATIENT_CLAIMS_03
		RIF2008.INPATIENT_CLAIMS_04
		RIF2008.INPATIENT_CLAIMS_05
		RIF2008.INPATIENT_CLAIMS_06
		RIF2008.INPATIENT_CLAIMS_07
		RIF2008.INPATIENT_CLAIMS_08
		RIF2008.INPATIENT_CLAIMS_09
		RIF2008.INPATIENT_CLAIMS_10
		RIF2008.INPATIENT_CLAIMS_11
		RIF2008.INPATIENT_CLAIMS_12;
RUN;


PROC SQL;
	DROP TABLE PL027710.InpatientStays_2008;
	CREATE TABLE PL027710.InpatientStays_2008 AS
	SELECT a.BENE_ID, a.CLM_ID, a.CLM_ADMSN_DT, a.NCH_BENE_DSCHRG_DT, a.CLM_FROM_DT, a.CLM_THRU_DT, a.PRVDR_NUM, 
		CASE
			WHEN a.ORG_NPI_NUM NE '' AND a.ORG_NPI_NUM NE '0000000000' THEN a.ORG_NPI_NUM
			WHEN a.ORG_NPI_NUM='' OR a.ORG_NPI_NUM='0000000000' THEN b.NPI
		ELSE ''
		END AS ORG_NPI_NUM,
		a.OP_PHYSN_UPIN,
		CASE 
			WHEN a.OP_PHYSN_NPI NE '' AND a.OP_PHYSN_NPI NE '0000000000' THEN a.OP_PHYSN_NPI
			WHEN a.OP_PHYSN_NPI='' OR a.OP_PHYSN_NPI='0000000000' THEN c.NPI
		ELSE ''
		END AS OP_PHYSN_NPI,
		a.CLM_DRG_CD, a.ADMTG_DGNS_CD, a.ICD_DGNS_CD1, a.PRNCPAL_DGNS_CD, a.ICD_PRCDR_CD1,
		a.CLM_PMT_AMT, a.CLM_TOT_CHRG_AMT, a.NCH_PRMRY_PYR_CLM_PD_AMT, a.NCH_IP_TOT_DDCTN_AMT,
		a.CLM_PMT_AMT + a.NCH_PRMRY_PYR_CLM_PD_AMT + a.NCH_IP_TOT_DDCTN_AMT AS Inpatient_Spend,
		a.ICD_DGNS_CD2, a.ICD_DGNS_CD3, a.ICD_DGNS_CD4, a.ICD_DGNS_CD5, a.ICD_DGNS_CD6, a.ICD_DGNS_CD7,
		a.ICD_DGNS_CD8, a.ICD_DGNS_CD9, a.ICD_DGNS_CD10, d.drgweight,
		a.ICD_PRCDR_CD2, a.ICD_PRCDR_CD3, a.ICD_PRCDR_CD4, a.ICD_PRCDR_CD5,
		a.ICD_PRCDR_CD6, a.ICD_PRCDR_CD7, a.ICD_PRCDR_CD8, a.ICD_PRCDR_CD9, a.ICD_PRCDR_CD10,
		a.PTNT_DSCHRG_STUS_CD AS DCHRG_STS
	FROM WORK.InpatientStays_2008 AS a
	LEFT JOIN PL027710.PRVN_NPI_Merge_2008 AS b
		ON a.PRVDR_NUM=b.PRVDR_NUM
	LEFT JOIN PL027710.UPIN_NPI_Merge_2008 AS c
		ON a.OP_PHYSN_UPIN=c.OP_PHYSN_UPIN
	LEFT JOIN (SELECT * FROM PL027710.DRG_Weights WHERE fyear=2008) AS d
		ON input(a.CLM_DRG_CD,18.)=d.drg
	WHERE CLM_SRC_IP_ADMSN_CD IN ("1","2","3")
		  AND (NCH_CLM_TYPE_CD="60")
		  AND (CLM_IP_ADMSN_TYPE_CD="3");
QUIT;



/* Create Table of Inpatient (Hospital Only) Stays for 2009 */
DATA WORK.InpatientStays_2009;
	SET	RIF2009.INPATIENT_CLAIMS_01
  		RIF2009.INPATIENT_CLAIMS_02
		RIF2009.INPATIENT_CLAIMS_03
		RIF2009.INPATIENT_CLAIMS_04
		RIF2009.INPATIENT_CLAIMS_05
		RIF2009.INPATIENT_CLAIMS_06
		RIF2009.INPATIENT_CLAIMS_07
		RIF2009.INPATIENT_CLAIMS_08
		RIF2009.INPATIENT_CLAIMS_09
		RIF2009.INPATIENT_CLAIMS_10
		RIF2009.INPATIENT_CLAIMS_11
		RIF2009.INPATIENT_CLAIMS_12;
RUN;


PROC SQL;
	DROP TABLE PL027710.InpatientStays_2009;
	CREATE TABLE PL027710.InpatientStays_2009 AS
	SELECT BENE_ID, CLM_ID, CLM_ADMSN_DT, NCH_BENE_DSCHRG_DT, CLM_FROM_DT, CLM_THRU_DT, PRVDR_NUM, ORG_NPI_NUM, OP_PHYSN_UPIN,
		OP_PHYSN_NPI, CLM_DRG_CD, ADMTG_DGNS_CD, ICD_DGNS_CD1, PRNCPAL_DGNS_CD, ICD_PRCDR_CD1,
		a.CLM_PMT_AMT, a.CLM_TOT_CHRG_AMT, a.NCH_PRMRY_PYR_CLM_PD_AMT, a.NCH_IP_TOT_DDCTN_AMT,
		a.CLM_PMT_AMT + a.NCH_PRMRY_PYR_CLM_PD_AMT + a.NCH_IP_TOT_DDCTN_AMT AS Inpatient_Spend,
		ICD_DGNS_CD2, ICD_DGNS_CD3, ICD_DGNS_CD4, ICD_DGNS_CD5, ICD_DGNS_CD6, ICD_DGNS_CD7,
		ICD_DGNS_CD8, ICD_DGNS_CD9, ICD_DGNS_CD10, b.drgweight,
		a.ICD_PRCDR_CD2, a.ICD_PRCDR_CD3, a.ICD_PRCDR_CD4, a.ICD_PRCDR_CD5,
		a.ICD_PRCDR_CD6, a.ICD_PRCDR_CD7, a.ICD_PRCDR_CD8, a.ICD_PRCDR_CD9, a.ICD_PRCDR_CD10,
		a.PTNT_DSCHRG_STUS_CD AS DCHRG_STS
	FROM WORK.InpatientStays_2009 as a
	LEFT JOIN (SELECT * FROM PL027710.DRG_Weights WHERE fyear=2009) AS b
		ON input(a.CLM_DRG_CD,18.)=b.drg
	WHERE CLM_SRC_IP_ADMSN_CD IN ("1","2","3")
		  AND (NCH_CLM_TYPE_CD="60")
		  AND (CLM_IP_ADMSN_TYPE_CD="3");
QUIT;


/* Create Table of Inpatient (Hospital Only) Stays for 2010 */
DATA WORK.InpatientStays_2010;
	SET	RIF2010.INPATIENT_CLAIMS_01
  		RIF2010.INPATIENT_CLAIMS_02
		RIF2010.INPATIENT_CLAIMS_03
		RIF2010.INPATIENT_CLAIMS_04
		RIF2010.INPATIENT_CLAIMS_05
		RIF2010.INPATIENT_CLAIMS_06
		RIF2010.INPATIENT_CLAIMS_07
		RIF2010.INPATIENT_CLAIMS_08
		RIF2010.INPATIENT_CLAIMS_09
		RIF2010.INPATIENT_CLAIMS_10
		RIF2010.INPATIENT_CLAIMS_11
		RIF2010.INPATIENT_CLAIMS_12;
RUN;


PROC SQL;
	DROP TABLE PL027710.InpatientStays_2010;
	CREATE TABLE PL027710.InpatientStays_2010 AS
	SELECT BENE_ID, CLM_ID, CLM_ADMSN_DT, NCH_BENE_DSCHRG_DT, CLM_FROM_DT, CLM_THRU_DT, PRVDR_NUM, ORG_NPI_NUM, OP_PHYSN_UPIN,
		OP_PHYSN_NPI, CLM_DRG_CD, ADMTG_DGNS_CD, ICD_DGNS_CD1, PRNCPAL_DGNS_CD, ICD_PRCDR_CD1,
		a.CLM_PMT_AMT, a.CLM_TOT_CHRG_AMT, a.NCH_PRMRY_PYR_CLM_PD_AMT, a.NCH_IP_TOT_DDCTN_AMT,
		a.CLM_PMT_AMT + a.NCH_PRMRY_PYR_CLM_PD_AMT + a.NCH_IP_TOT_DDCTN_AMT AS Inpatient_Spend,
		ICD_DGNS_CD2, ICD_DGNS_CD3, ICD_DGNS_CD4, ICD_DGNS_CD5, ICD_DGNS_CD6, ICD_DGNS_CD7,
		ICD_DGNS_CD8, ICD_DGNS_CD9, ICD_DGNS_CD10, b.drgweight,
		a.ICD_PRCDR_CD2, a.ICD_PRCDR_CD3, a.ICD_PRCDR_CD4, a.ICD_PRCDR_CD5,
		a.ICD_PRCDR_CD6, a.ICD_PRCDR_CD7, a.ICD_PRCDR_CD8, a.ICD_PRCDR_CD9, a.ICD_PRCDR_CD10,
		a.PTNT_DSCHRG_STUS_CD AS DCHRG_STS
	FROM WORK.InpatientStays_2010 as a
	LEFT JOIN (SELECT * FROM PL027710.DRG_Weights WHERE fyear=2010) AS b
		ON input(a.CLM_DRG_CD,18.)=b.drg
	WHERE CLM_SRC_IP_ADMSN_CD IN ("1","2","3")
		  AND (NCH_CLM_TYPE_CD="60")
		  AND (CLM_IP_ADMSN_TYPE_CD="3");
QUIT;


/* Create Table of Inpatient (Hospital Only) Stays for 2011 */
DATA WORK.InpatientStays_2011;
	SET	RIF2011.INPATIENT_CLAIMS_01
  		RIF2011.INPATIENT_CLAIMS_02
		RIF2011.INPATIENT_CLAIMS_03
		RIF2011.INPATIENT_CLAIMS_04
		RIF2011.INPATIENT_CLAIMS_05
		RIF2011.INPATIENT_CLAIMS_06
		RIF2011.INPATIENT_CLAIMS_07
		RIF2011.INPATIENT_CLAIMS_08
		RIF2011.INPATIENT_CLAIMS_09
		RIF2011.INPATIENT_CLAIMS_10
		RIF2011.INPATIENT_CLAIMS_11
		RIF2011.INPATIENT_CLAIMS_12;
RUN;


PROC SQL;
	DROP TABLE PL027710.InpatientStays_2011;
	CREATE TABLE PL027710.InpatientStays_2011 AS
	SELECT BENE_ID, CLM_ID, CLM_ADMSN_DT, NCH_BENE_DSCHRG_DT, CLM_FROM_DT, CLM_THRU_DT, PRVDR_NUM, ORG_NPI_NUM, OP_PHYSN_UPIN,
		OP_PHYSN_NPI, CLM_DRG_CD, ADMTG_DGNS_CD, ICD_DGNS_CD1, PRNCPAL_DGNS_CD, ICD_PRCDR_CD1,
		a.CLM_PMT_AMT, a.CLM_TOT_CHRG_AMT, a.NCH_PRMRY_PYR_CLM_PD_AMT, a.NCH_IP_TOT_DDCTN_AMT,
		a.CLM_PMT_AMT + a.NCH_PRMRY_PYR_CLM_PD_AMT + a.NCH_IP_TOT_DDCTN_AMT AS Inpatient_Spend,
		ICD_DGNS_CD2, ICD_DGNS_CD3, ICD_DGNS_CD4, ICD_DGNS_CD5, ICD_DGNS_CD6, ICD_DGNS_CD7,
		ICD_DGNS_CD8, ICD_DGNS_CD9, ICD_DGNS_CD10, b.drgweight,
		a.ICD_PRCDR_CD2, a.ICD_PRCDR_CD3, a.ICD_PRCDR_CD4, a.ICD_PRCDR_CD5,
		a.ICD_PRCDR_CD6, a.ICD_PRCDR_CD7, a.ICD_PRCDR_CD8, a.ICD_PRCDR_CD9, a.ICD_PRCDR_CD10,
		a.PTNT_DSCHRG_STUS_CD AS DCHRG_STS
	FROM WORK.InpatientStays_2011 as a
	LEFT JOIN (SELECT * FROM PL027710.DRG_Weights WHERE fyear=2011) AS b
		ON input(a.CLM_DRG_CD,18.)=b.drg
	WHERE CLM_SRC_IP_ADMSN_CD IN ("1","2","3")
		  AND (NCH_CLM_TYPE_CD="60")
		  AND (CLM_IP_ADMSN_TYPE_CD="3");
QUIT;


/* Create Table of Inpatient (Hospital Only) Stays for 2012 */
DATA WORK.InpatientStays_2012;
	SET	RIF2012.INPATIENT_CLAIMS_01
  		RIF2012.INPATIENT_CLAIMS_02
		RIF2012.INPATIENT_CLAIMS_03
		RIF2012.INPATIENT_CLAIMS_04
		RIF2012.INPATIENT_CLAIMS_05
		RIF2012.INPATIENT_CLAIMS_06
		RIF2012.INPATIENT_CLAIMS_07
		RIF2012.INPATIENT_CLAIMS_08
		RIF2012.INPATIENT_CLAIMS_09
		RIF2012.INPATIENT_CLAIMS_10
		RIF2012.INPATIENT_CLAIMS_11
		RIF2012.INPATIENT_CLAIMS_12;
RUN;


PROC SQL;
	DROP TABLE PL027710.InpatientStays_2012;
	CREATE TABLE PL027710.InpatientStays_2012 AS
	SELECT BENE_ID, CLM_ID, CLM_ADMSN_DT, NCH_BENE_DSCHRG_DT, CLM_FROM_DT, CLM_THRU_DT, PRVDR_NUM, ORG_NPI_NUM, OP_PHYSN_UPIN,
		OP_PHYSN_NPI, CLM_DRG_CD, ADMTG_DGNS_CD, ICD_DGNS_CD1, PRNCPAL_DGNS_CD, ICD_PRCDR_CD1,
		a.CLM_PMT_AMT, a.CLM_TOT_CHRG_AMT, a.NCH_PRMRY_PYR_CLM_PD_AMT, a.NCH_IP_TOT_DDCTN_AMT,
		a.CLM_PMT_AMT + a.NCH_PRMRY_PYR_CLM_PD_AMT + a.NCH_IP_TOT_DDCTN_AMT AS Inpatient_Spend,
		ICD_DGNS_CD2, ICD_DGNS_CD3, ICD_DGNS_CD4, ICD_DGNS_CD5, ICD_DGNS_CD6, ICD_DGNS_CD7,
		ICD_DGNS_CD8, ICD_DGNS_CD9, ICD_DGNS_CD10, b.drgweight,
		a.ICD_PRCDR_CD2, a.ICD_PRCDR_CD3, a.ICD_PRCDR_CD4, a.ICD_PRCDR_CD5,
		a.ICD_PRCDR_CD6, a.ICD_PRCDR_CD7, a.ICD_PRCDR_CD8, a.ICD_PRCDR_CD9, a.ICD_PRCDR_CD10,
		a.PTNT_DSCHRG_STUS_CD AS DCHRG_STS
	FROM WORK.InpatientStays_2012 as a
	LEFT JOIN (SELECT * FROM PL027710.DRG_Weights WHERE fyear=2012) AS b
		ON input(a.CLM_DRG_CD,18.)=b.drg
	WHERE CLM_SRC_IP_ADMSN_CD IN ("1","2","3")
		  AND (NCH_CLM_TYPE_CD="60")
		  AND (CLM_IP_ADMSN_TYPE_CD="3");
QUIT;


/* Create Table of Inpatient (Hospital Only) Stays for 2013 */
DATA WORK.InpatientStays_2013;
	SET	RIF2013.INPATIENT_CLAIMS_01
  		RIF2013.INPATIENT_CLAIMS_02
		RIF2013.INPATIENT_CLAIMS_03
		RIF2013.INPATIENT_CLAIMS_04
		RIF2013.INPATIENT_CLAIMS_05
		RIF2013.INPATIENT_CLAIMS_06
		RIF2013.INPATIENT_CLAIMS_07
		RIF2013.INPATIENT_CLAIMS_08
		RIF2013.INPATIENT_CLAIMS_09
		RIF2013.INPATIENT_CLAIMS_10
		RIF2013.INPATIENT_CLAIMS_11
		RIF2013.INPATIENT_CLAIMS_12;
RUN;


PROC SQL;
	DROP TABLE PL027710.InpatientStays_2013;
	CREATE TABLE PL027710.InpatientStays_2013 AS
	SELECT BENE_ID, CLM_ID, CLM_ADMSN_DT, NCH_BENE_DSCHRG_DT, CLM_FROM_DT, CLM_THRU_DT, PRVDR_NUM, ORG_NPI_NUM, OP_PHYSN_UPIN,
		OP_PHYSN_NPI, CLM_DRG_CD, ADMTG_DGNS_CD, ICD_DGNS_CD1, PRNCPAL_DGNS_CD, ICD_PRCDR_CD1,
		a.CLM_PMT_AMT, a.CLM_TOT_CHRG_AMT, a.NCH_PRMRY_PYR_CLM_PD_AMT, a.NCH_IP_TOT_DDCTN_AMT,
		a.CLM_PMT_AMT + a.NCH_PRMRY_PYR_CLM_PD_AMT + a.NCH_IP_TOT_DDCTN_AMT AS Inpatient_Spend,
		ICD_DGNS_CD2, ICD_DGNS_CD3, ICD_DGNS_CD4, ICD_DGNS_CD5, ICD_DGNS_CD6, ICD_DGNS_CD7,
		ICD_DGNS_CD8, ICD_DGNS_CD9, ICD_DGNS_CD10, b.drgweight,
		a.ICD_PRCDR_CD2, a.ICD_PRCDR_CD3, a.ICD_PRCDR_CD4, a.ICD_PRCDR_CD5,
		a.ICD_PRCDR_CD6, a.ICD_PRCDR_CD7, a.ICD_PRCDR_CD8, a.ICD_PRCDR_CD9, a.ICD_PRCDR_CD10,
		a.PTNT_DSCHRG_STUS_CD AS DCHRG_STS
	FROM WORK.InpatientStays_2013 as a
	LEFT JOIN (SELECT * FROM PL027710.DRG_Weights WHERE fyear=2013) AS b
		ON input(a.CLM_DRG_CD,18.)=b.drg
	WHERE CLM_SRC_IP_ADMSN_CD IN ("1","2","3")
		  AND (NCH_CLM_TYPE_CD="60")
		  AND (CLM_IP_ADMSN_TYPE_CD="3");
QUIT;


/* Create Table of Inpatient (Hospital Only) Stays for 2014 */
DATA WORK.InpatientStays_2014;
	SET	RIF2014.INPATIENT_CLAIMS_01
  		RIF2014.INPATIENT_CLAIMS_02
		RIF2014.INPATIENT_CLAIMS_03
		RIF2014.INPATIENT_CLAIMS_04
		RIF2014.INPATIENT_CLAIMS_05
		RIF2014.INPATIENT_CLAIMS_06
		RIF2014.INPATIENT_CLAIMS_07
		RIF2014.INPATIENT_CLAIMS_08
		RIF2014.INPATIENT_CLAIMS_09
		RIF2014.INPATIENT_CLAIMS_10
		RIF2014.INPATIENT_CLAIMS_11
		RIF2014.INPATIENT_CLAIMS_12;
RUN;


PROC SQL;
	DROP TABLE PL027710.InpatientStays_2014;
	CREATE TABLE PL027710.InpatientStays_2014 AS
	SELECT BENE_ID, CLM_ID, CLM_ADMSN_DT, NCH_BENE_DSCHRG_DT, CLM_FROM_DT, CLM_THRU_DT, PRVDR_NUM, ORG_NPI_NUM, OP_PHYSN_UPIN,
		OP_PHYSN_NPI, CLM_DRG_CD, ADMTG_DGNS_CD, ICD_DGNS_CD1, PRNCPAL_DGNS_CD, ICD_PRCDR_CD1,
		a.CLM_PMT_AMT, a.CLM_TOT_CHRG_AMT, a.NCH_PRMRY_PYR_CLM_PD_AMT, a.NCH_IP_TOT_DDCTN_AMT,
		a.CLM_PMT_AMT + a.NCH_PRMRY_PYR_CLM_PD_AMT + a.NCH_IP_TOT_DDCTN_AMT AS Inpatient_Spend,
		ICD_DGNS_CD2, ICD_DGNS_CD3, ICD_DGNS_CD4, ICD_DGNS_CD5, ICD_DGNS_CD6, ICD_DGNS_CD7,
		ICD_DGNS_CD8, ICD_DGNS_CD9, ICD_DGNS_CD10, b.drgweight,
		a.ICD_PRCDR_CD2, a.ICD_PRCDR_CD3, a.ICD_PRCDR_CD4, a.ICD_PRCDR_CD5,
		a.ICD_PRCDR_CD6, a.ICD_PRCDR_CD7, a.ICD_PRCDR_CD8, a.ICD_PRCDR_CD9, a.ICD_PRCDR_CD10,
		a.PTNT_DSCHRG_STUS_CD AS DCHRG_STS
	FROM WORK.InpatientStays_2014 as a
	LEFT JOIN (SELECT * FROM PL027710.DRG_Weights WHERE fyear=2014) AS b
		ON input(a.CLM_DRG_CD,18.)=b.drg
	WHERE CLM_SRC_IP_ADMSN_CD IN ("1","2","3")
		  AND (NCH_CLM_TYPE_CD="60")
		  AND (CLM_IP_ADMSN_TYPE_CD="3");
QUIT;


/* Create Table of Inpatient (Hospital Only) Stays for 2015 */
DATA WORK.InpatientStays_2015;
	SET	RIF2015.INPATIENT_CLAIMS_01
  		RIF2015.INPATIENT_CLAIMS_02
		RIF2015.INPATIENT_CLAIMS_03
		RIF2015.INPATIENT_CLAIMS_04
		RIF2015.INPATIENT_CLAIMS_05
		RIF2015.INPATIENT_CLAIMS_06
		RIF2015.INPATIENT_CLAIMS_07
		RIF2015.INPATIENT_CLAIMS_08
		RIF2015.INPATIENT_CLAIMS_09
		RIF2015.INPATIENT_CLAIMS_10
		RIF2015.INPATIENT_CLAIMS_11
		RIF2015.INPATIENT_CLAIMS_12;
RUN;


PROC SQL;
	DROP TABLE PL027710.InpatientStays_2015;
	CREATE TABLE PL027710.InpatientStays_2015 AS
	SELECT BENE_ID, CLM_ID, CLM_ADMSN_DT, NCH_BENE_DSCHRG_DT, CLM_FROM_DT, CLM_THRU_DT, PRVDR_NUM, ORG_NPI_NUM, OP_PHYSN_UPIN,
		OP_PHYSN_NPI, CLM_DRG_CD, ADMTG_DGNS_CD, ICD_DGNS_CD1, PRNCPAL_DGNS_CD, ICD_PRCDR_CD1,
		a.CLM_PMT_AMT, a.CLM_TOT_CHRG_AMT, a.NCH_PRMRY_PYR_CLM_PD_AMT, a.NCH_IP_TOT_DDCTN_AMT,
		a.CLM_PMT_AMT + a.NCH_PRMRY_PYR_CLM_PD_AMT + a.NCH_IP_TOT_DDCTN_AMT AS Inpatient_Spend,
		ICD_DGNS_CD2, ICD_DGNS_CD3, ICD_DGNS_CD4, ICD_DGNS_CD5, ICD_DGNS_CD6, ICD_DGNS_CD7,
		ICD_DGNS_CD8, ICD_DGNS_CD9, ICD_DGNS_CD10, b.drgweight,
		a.ICD_PRCDR_CD2, a.ICD_PRCDR_CD3, a.ICD_PRCDR_CD4, a.ICD_PRCDR_CD5,
		a.ICD_PRCDR_CD6, a.ICD_PRCDR_CD7, a.ICD_PRCDR_CD8, a.ICD_PRCDR_CD9, a.ICD_PRCDR_CD10,
		a.PTNT_DSCHRG_STUS_CD AS DCHRG_STS
	FROM WORK.InpatientStays_2015 as a
	LEFT JOIN (SELECT * FROM PL027710.DRG_Weights WHERE fyear=2015) AS b
		ON input(a.CLM_DRG_CD,18.)=b.drg
	WHERE CLM_SRC_IP_ADMSN_CD IN ("1","2","3")
		  AND (NCH_CLM_TYPE_CD="60")
		  AND (CLM_IP_ADMSN_TYPE_CD="3");
QUIT;

