---
title: "Owning the Agent: Hospital Influence on Physician Behaviors"
---

```{css, echo=FALSE}
.section h2 {
    padding-top: 94px;
    margin-top: -71px;
}

.title {
    display: none
}
```


**Haizhen Lin**  
Kelly School of Business • Indiana University<br>
Research Associate • National Bureau of Economic Research<br>
[personal website](https://host.kelley.iu.edu/hzlin/)


**Ian McCarthy**  
Department of Economics • Emory University<br>
Research Associate • National Bureau of Economic Research<br>
[ianmccarthyecon.com](https://www.ianmccarthyecon.com) • [\@ianhealthecon](https://twitter.com/ianhealthecon)


**Michael Richards**  
Department of Economics • Baylor University<br>
[personal website](https://michaelrichards.webstarts.com/)


---

Welcome! This is a small site designed primarily to house materials for our project, "Owning the Agent: Hospital Influence on Physician Behaviors." Use the top menu to navigate the site, and you can find all of the source code at the GitHub repository, [here](https://github.com/imccart/physician-hospital-vi). Links to the working paper, and our related paper on vertical integration and hospital pricing, are listed below. This project was also supported in-part by grant number R00HS022431 from the Agency for Healthcare Research and Quality.


---

"Owning the Agent: Hospital Influence on Physician Behaviors" <br>

<a href=https://www.nber.org/papers/w28859><i class="fas fa-download"> **Download Working Paper**</i></a><br>

<a href=https://data.nber.org/data-appendix/w28859/healthcare-vi-appendix.pdf><i class="fas fa-download"> **Download Supplemental Appendix**</i></a><br>


---

"Hospital Prices Following Integration with Physician Practices", Journal of Health Economics, 2021 <br>

<a href=https://www.sciencedirect.com/science/article/pii/S0167629621000291><i class="fas fa-download"> **Download Paper**</i></a><br>
