---
title: "Presentations"
---

We've presented several different versions of this paper over the past few years. As papers and research projects tend to go, the first versions of this paper look very different than the current version. That's especially true for this project, where our outcomes have changed over time to incorporate a much broader/larger-scale measure of physician behavior and health care utilization. Links to individual presentations are below.

**2018**

- [Emory, Economics Lunch and Learn](presentations/emory-lunchandlearn-2018/McCarthy Physician VI Slides.pdf)
- [Emory, Rollins School of Public Health](presentations/emory-rollins-2018/McCarthy Physician VI Slides.pdf)
- [John's Hopkins University](presentations/jhu-2018/JHU_Slides_169.pdf)
- [George Washington University](presentations/gwu-2018/McCarthy Physician VI Slides.pdf)
- [University of Nevada, Las Vegas](presentations/unlv-2018/McCarthy Physician VI Slides.pdf)

**2019**

- [Indiana University/Purdue University](presentations/iupui-2019/McCarthy Physician VI Slides.pdf)
- [Indiana University](presentations/iu-2019/McCarthy Physician VI Slides.pdf)
- [West Virginia University](presentations/wvu-2019/McCarthy Physician VI Slides.pdf)
- [Southeastern Health Economics Study Group](presentations/shesg-2019/McCarthy Physician VI Slides.pdf)

**2020**

- [American Economic Association](presentations/aea-2020/McCarthy Physician VI Slides.pdf)
