/* ------------------------------------------------------------ */
/* TITLE:		 Create Carrier File Data				        */
/* AUTHOR:		 Ian McCarthy									*/
/* 				 Emory University								*/
/* DATE CREATED: 1/22/2016										*/
/* DATE EDITED:  1/31/2020										*/
/* CODE FILE ORDER: 13 of 13									*/
/* NOTES:														*/
/*   BENE_CC  Master beneficiary summary file 					*/
/*   MCBSxxxx Medicare Current Beneficiary Survey (Year xxxx) 	*/
/*   MCBSXWLK MCBS Crosswalk 									*/
/*   RIFSxxxx Out/Inpatient and Carrier claims (Year xxxx)   	*/
/*   Medpar   Inpatient claims  								*/
/*   -- File outputs the following tables to IMC969SL:			*/
/*		Carrier_20XX											*/
/* ------------------------------------------------------------ */

PROC SQL;
	DROP TABLE WORK.HCPCS;
	CREATE TABLE WORK.HCPCS AS
	SELECT DISTINCT BENE_ID, PRF_PHYSN_NPI, CLM_THRU_DT, HCPCS_CD
	FROM IN027710.BCARLINEK07_R6723
	WHERE HCPCS_CD IS NOT NULL;
QUIT;

PROC TRANSPOSE data=WORK.HCPCS out=WORK.ReshapeHCPCS
	(drop=_NAME_ _LABEL_) prefix=Code;
	var HCPCS_CD;
	by BENE_ID PRF_PHYSN_NPI CLM_THRU_DT;
RUN;

PROC SQL;
  DROP TABLE WORK.Carrier_2007a;
  CREATE TABLE WORK.Carrier_2007a AS
  SELECT a.PRF_PHYSN_NPI AS Physician_ID, a.BENE_ID, Count(a.BENE_ID) AS Carrier_Claims, 
		sum(a.LINE_NCH_PMT_AMT) as Carrier_Pay, sum(a.LINE_SBMTD_CHRG_AMT) AS Carrier_Charge,
		a.CLM_THRU_DT AS Claim_Date, 2007 AS Year
  FROM IN027710.BCARLINEK07_R6723 AS a
  GROUP BY a.PRF_PHYSN_NPI, a.BENE_ID, a.CLM_THRU_DT
  ORDER BY a.BENE_ID, a.PRF_PHYSN_NPI, a.CLM_THRU_DT;
QUIT;


PROC SQL;
  DROP TABLE WORK.Carrier_2007;
  CREATE TABLE WORK.Carrier_2007 AS
  SELECT a.*, b.CODE1, b.CODE2, b.CODE3, b.CODE4, b.CODE5, b.CODE6, 
		b.CODE7, b.CODE8, b.CODE9, b.CODE10
  FROM WORK.Carrier_2007a AS a
  LEFT JOIN WORK.ReshapeHCPCS AS b
  	ON a.BENE_ID=b.BENE_ID AND a.Physician_ID=b.PRF_PHYSN_NPI AND a.Claim_Date=b.CLM_THRU_DT;
QUIT;



PROC SQL;
	DROP TABLE WORK.HCPCS;
	CREATE TABLE WORK.HCPCS AS
	SELECT DISTINCT BENE_ID, PRF_PHYSN_NPI, CLM_THRU_DT, HCPCS_CD
	FROM IN027710.BCARLINEK08_R6723
	WHERE HCPCS_CD IS NOT NULL;
QUIT;

PROC TRANSPOSE data=WORK.HCPCS out=WORK.ReshapeHCPCS
	(drop=_NAME_ _LABEL_) prefix=Code;
	var HCPCS_CD;
	by BENE_ID PRF_PHYSN_NPI CLM_THRU_DT;
RUN;

PROC SQL;
  DROP TABLE WORK.Carrier_2008a;
  CREATE TABLE WORK.Carrier_2008a AS
  SELECT a.PRF_PHYSN_NPI AS Physician_ID, a.BENE_ID, Count(a.BENE_ID) AS Carrier_Claims, 
		sum(a.LINE_NCH_PMT_AMT) as Carrier_Pay, sum(a.LINE_SBMTD_CHRG_AMT) AS Carrier_Charge,
		a.CLM_THRU_DT AS Claim_Date, 2008 AS Year
  FROM IN027710.BCARLINEK08_R6723 AS a
  GROUP BY a.PRF_PHYSN_NPI, a.BENE_ID, a.CLM_THRU_DT
  ORDER BY a.BENE_ID, a.PRF_PHYSN_NPI, a.CLM_THRU_DT;
QUIT;

PROC SQL;
  DROP TABLE WORK.Carrier_2008;
  CREATE TABLE WORK.Carrier_2008 AS
  SELECT a.*, b.CODE1, b.CODE2, b.CODE3, b.CODE4, b.CODE5, b.CODE6, 
		b.CODE7, b.CODE8, b.CODE9, b.CODE10
  FROM WORK.Carrier_2008a AS a
  LEFT JOIN WORK.ReshapeHCPCS AS b
  	ON a.BENE_ID=b.BENE_ID AND a.Physician_ID=b.PRF_PHYSN_NPI AND a.Claim_Date=b.CLM_THRU_DT;
QUIT;



PROC SQL;
	DROP TABLE WORK.HCPCS;
	CREATE TABLE WORK.HCPCS AS
	SELECT DISTINCT BENE_ID, PRF_PHYSN_NPI, CLM_THRU_DT, HCPCS_CD
	FROM IN027710.BCARLINEJ09_R4585
	WHERE HCPCS_CD IS NOT NULL;
QUIT;

PROC TRANSPOSE data=WORK.HCPCS out=WORK.ReshapeHCPCS
	(drop=_NAME_ _LABEL_) prefix=Code;
	var HCPCS_CD;
	by BENE_ID PRF_PHYSN_NPI CLM_THRU_DT;
RUN;

PROC SQL;
  DROP TABLE WORK.Carrier_2009a;
  CREATE TABLE WORK.Carrier_2009a AS
  SELECT a.PRF_PHYSN_NPI AS Physician_ID, a.BENE_ID, Count(a.BENE_ID) AS Carrier_Claims, 
		sum(a.LINE_NCH_PMT_AMT) as Carrier_Pay, sum(a.LINE_SBMTD_CHRG_AMT) AS Carrier_Charge,
		a.CLM_THRU_DT AS Claim_Date, 2009 AS Year
  FROM IN027710.BCARLINEJ09_R4585 AS a
  GROUP BY a.PRF_PHYSN_NPI, a.BENE_ID, a.CLM_THRU_DT
  ORDER BY a.BENE_ID, a.PRF_PHYSN_NPI, a.CLM_THRU_DT;
QUIT;


PROC SQL;
  DROP TABLE WORK.Carrier_2009;
  CREATE TABLE WORK.Carrier_2009 AS
  SELECT a.*, b.CODE1, b.CODE2, b.CODE3, b.CODE4, b.CODE5, b.CODE6, 
		b.CODE7, b.CODE8, b.CODE9, b.CODE10
  FROM WORK.Carrier_2009a AS a
  LEFT JOIN WORK.ReshapeHCPCS AS b
  	ON a.BENE_ID=b.BENE_ID AND a.Physician_ID=b.PRF_PHYSN_NPI AND a.Claim_Date=b.CLM_THRU_DT;
QUIT;



PROC SQL;
	DROP TABLE WORK.HCPCS;
	CREATE TABLE WORK.HCPCS AS
	SELECT DISTINCT BENE_ID, PRF_PHYSN_NPI, CLM_THRU_DT, HCPCS_CD
	FROM IN027710.BCARLINEJ10_R4585
	WHERE HCPCS_CD IS NOT NULL;
QUIT;

PROC TRANSPOSE data=WORK.HCPCS out=WORK.ReshapeHCPCS
	(drop=_NAME_ _LABEL_) prefix=Code;
	var HCPCS_CD;
	by BENE_ID PRF_PHYSN_NPI CLM_THRU_DT;
RUN;

PROC SQL;
  DROP TABLE WORK.Carrier_2010a;
  CREATE TABLE WORK.Carrier_2010a AS
  SELECT a.PRF_PHYSN_NPI AS Physician_ID, a.BENE_ID, Count(a.BENE_ID) AS Carrier_Claims, 
		sum(a.LINE_NCH_PMT_AMT) as Carrier_Pay, sum(a.LINE_SBMTD_CHRG_AMT) AS Carrier_Charge,
		a.CLM_THRU_DT AS Claim_Date, 2010 AS Year
  FROM IN027710.BCARLINEJ10_R4585 AS a
  GROUP BY a.PRF_PHYSN_NPI, a.BENE_ID, a.CLM_THRU_DT
  ORDER BY a.BENE_ID, a.PRF_PHYSN_NPI, a.CLM_THRU_DT;
QUIT;

PROC SQL;
  DROP TABLE WORK.Carrier_2010;
  CREATE TABLE WORK.Carrier_2010 AS
  SELECT a.*, b.CODE1, b.CODE2, b.CODE3, b.CODE4, b.CODE5, b.CODE6, 
		b.CODE7, b.CODE8, b.CODE9, b.CODE10
  FROM WORK.Carrier_2010a AS a
  LEFT JOIN WORK.ReshapeHCPCS AS b
  	ON a.BENE_ID=b.BENE_ID AND a.Physician_ID=b.PRF_PHYSN_NPI AND a.Claim_Date=b.CLM_THRU_DT;
QUIT;


PROC SQL;
	DROP TABLE WORK.HCPCS;
	CREATE TABLE WORK.HCPCS AS
	SELECT DISTINCT BENE_ID, PRF_PHYSN_NPI, CLM_THRU_DT, HCPCS_CD
	FROM IN027710.BCARLINEJ11_R4585
	WHERE HCPCS_CD IS NOT NULL;
QUIT;

PROC TRANSPOSE data=WORK.HCPCS out=WORK.ReshapeHCPCS
	(drop=_NAME_ _LABEL_) prefix=Code;
	var HCPCS_CD;
	by BENE_ID PRF_PHYSN_NPI CLM_THRU_DT;
RUN;

PROC SQL;
  DROP TABLE WORK.Carrier_2011a;
  CREATE TABLE WORK.Carrier_2011a AS
  SELECT a.PRF_PHYSN_NPI AS Physician_ID, a.BENE_ID, Count(a.BENE_ID) AS Carrier_Claims, 
		sum(a.LINE_NCH_PMT_AMT) as Carrier_Pay, sum(a.LINE_SBMTD_CHRG_AMT) AS Carrier_Charge,
		a.CLM_THRU_DT AS Claim_Date, 2011 AS Year
  FROM IN027710.BCARLINEJ11_R4585 AS a
  GROUP BY a.PRF_PHYSN_NPI, a.BENE_ID, a.CLM_THRU_DT
  ORDER BY a.BENE_ID, a.PRF_PHYSN_NPI, a.CLM_THRU_DT;
QUIT;

PROC SQL;
  DROP TABLE WORK.Carrier_2011;
  CREATE TABLE WORK.Carrier_2011 AS
  SELECT a.*, b.CODE1, b.CODE2, b.CODE3, b.CODE4, b.CODE5, b.CODE6, 
		b.CODE7, b.CODE8, b.CODE9, b.CODE10
  FROM WORK.Carrier_2011a AS a
  LEFT JOIN WORK.ReshapeHCPCS AS b
  	ON a.BENE_ID=b.BENE_ID AND a.Physician_ID=b.PRF_PHYSN_NPI AND a.Claim_Date=b.CLM_THRU_DT;
QUIT;


PROC SQL;
	DROP TABLE WORK.HCPCS;
	CREATE TABLE WORK.HCPCS AS
	SELECT DISTINCT BENE_ID, PRF_PHYSN_NPI, CLM_THRU_DT, HCPCS_CD
	FROM IN027710.BCARLINEK12_R6723
	WHERE HCPCS_CD IS NOT NULL;
QUIT;

PROC TRANSPOSE data=WORK.HCPCS out=WORK.ReshapeHCPCS
	(drop=_NAME_ _LABEL_) prefix=Code;
	var HCPCS_CD;
	by BENE_ID PRF_PHYSN_NPI CLM_THRU_DT;
RUN;

PROC SQL;
  DROP TABLE WORK.Carrier_2012a;
  CREATE TABLE WORK.Carrier_2012a AS
  SELECT a.PRF_PHYSN_NPI AS Physician_ID, a.BENE_ID, Count(a.BENE_ID) AS Carrier_Claims, 
		sum(a.LINE_NCH_PMT_AMT) as Carrier_Pay, sum(a.LINE_SBMTD_CHRG_AMT) AS Carrier_Charge,
		a.CLM_THRU_DT AS Claim_Date, 2012 AS Year
  FROM IN027710.BCARLINEK12_R6723 AS a
  GROUP BY a.PRF_PHYSN_NPI, a.BENE_ID, a.CLM_THRU_DT
  ORDER BY a.BENE_ID, a.PRF_PHYSN_NPI, a.CLM_THRU_DT;
QUIT;

PROC SQL;
  DROP TABLE WORK.Carrier_2012;
  CREATE TABLE WORK.Carrier_2012 AS
  SELECT a.*, b.CODE1, b.CODE2, b.CODE3, b.CODE4, b.CODE5, b.CODE6, 
		b.CODE7, b.CODE8, b.CODE9, b.CODE10
  FROM WORK.Carrier_2012a AS a
  LEFT JOIN WORK.ReshapeHCPCS AS b
  	ON a.BENE_ID=b.BENE_ID AND a.Physician_ID=b.PRF_PHYSN_NPI AND a.Claim_Date=b.CLM_THRU_DT;
QUIT;


PROC SQL;
	DROP TABLE WORK.HCPCS;
	CREATE TABLE WORK.HCPCS AS
	SELECT DISTINCT BENE_ID, PRF_PHYSN_NPI, CLM_THRU_DT, HCPCS_CD
	FROM IN027710.BCARLINEK13_R6723
	WHERE HCPCS_CD IS NOT NULL;
QUIT;

PROC TRANSPOSE data=WORK.HCPCS out=WORK.ReshapeHCPCS
	(drop=_NAME_ _LABEL_) prefix=Code;
	var HCPCS_CD;
	by BENE_ID PRF_PHYSN_NPI CLM_THRU_DT;
RUN;

PROC SQL;
  DROP TABLE WORK.Carrier_2013a;
  CREATE TABLE WORK.Carrier_2013a AS
  SELECT a.PRF_PHYSN_NPI AS Physician_ID, a.BENE_ID, Count(a.BENE_ID) AS Carrier_Claims, 
		sum(a.LINE_NCH_PMT_AMT) as Carrier_Pay, sum(a.LINE_SBMTD_CHRG_AMT) AS Carrier_Charge,
		a.CLM_THRU_DT AS Claim_Date, 2013 AS Year
  FROM IN027710.BCARLINEK13_R6723 AS a
  GROUP BY a.PRF_PHYSN_NPI, a.BENE_ID, a.CLM_THRU_DT
  ORDER BY a.BENE_ID, a.PRF_PHYSN_NPI, a.CLM_THRU_DT;
QUIT;

PROC SQL;
  DROP TABLE WORK.Carrier_2013;
  CREATE TABLE WORK.Carrier_2013 AS
  SELECT a.*, b.CODE1, b.CODE2, b.CODE3, b.CODE4, b.CODE5, b.CODE6, 
		b.CODE7, b.CODE8, b.CODE9, b.CODE10
  FROM WORK.Carrier_2013a AS a
  LEFT JOIN WORK.ReshapeHCPCS AS b
  	ON a.BENE_ID=b.BENE_ID AND a.Physician_ID=b.PRF_PHYSN_NPI AND a.Claim_Date=b.CLM_THRU_DT;
QUIT;


PROC SQL;
	DROP TABLE WORK.HCPCS;
	CREATE TABLE WORK.HCPCS AS
	SELECT DISTINCT BENE_ID, PRF_PHYSN_NPI, CLM_THRU_DT, HCPCS_CD
	FROM IN027710.BCARLINEK14_R6723
	WHERE HCPCS_CD IS NOT NULL;
QUIT;

PROC TRANSPOSE data=WORK.HCPCS out=WORK.ReshapeHCPCS
	(drop=_NAME_ _LABEL_) prefix=Code;
	var HCPCS_CD;
	by BENE_ID PRF_PHYSN_NPI CLM_THRU_DT;
RUN;

PROC SQL;
  DROP TABLE WORK.Carrier_2014a;
  CREATE TABLE WORK.Carrier_2014a AS
  SELECT a.PRF_PHYSN_NPI AS Physician_ID, a.BENE_ID, Count(a.BENE_ID) AS Carrier_Claims, 
		sum(a.LINE_NCH_PMT_AMT) as Carrier_Pay, sum(a.LINE_SBMTD_CHRG_AMT) AS Carrier_Charge,
		a.CLM_THRU_DT AS Claim_Date, 2014 AS Year
  FROM IN027710.BCARLINEK14_R6723 AS a
  GROUP BY a.PRF_PHYSN_NPI, a.BENE_ID, a.CLM_THRU_DT
  ORDER BY a.BENE_ID, a.PRF_PHYSN_NPI, a.CLM_THRU_DT;
QUIT;

PROC SQL;
  DROP TABLE WORK.Carrier_2014;
  CREATE TABLE WORK.Carrier_2014 AS
  SELECT a.*, b.CODE1, b.CODE2, b.CODE3, b.CODE4, b.CODE5, b.CODE6, 
		b.CODE7, b.CODE8, b.CODE9, b.CODE10
  FROM WORK.Carrier_2014a AS a
  LEFT JOIN WORK.ReshapeHCPCS AS b
  	ON a.BENE_ID=b.BENE_ID AND a.Physician_ID=b.PRF_PHYSN_NPI AND a.Claim_Date=b.CLM_THRU_DT;
QUIT;


PROC SQL;
	DROP TABLE WORK.HCPCS;
	CREATE TABLE WORK.HCPCS AS
	SELECT DISTINCT BENE_ID, PRF_PHYSN_NPI, CLM_THRU_DT, HCPCS_CD
	FROM IN027710.BCARLINEK15_R6723
	WHERE HCPCS_CD IS NOT NULL;
QUIT;

PROC TRANSPOSE data=WORK.HCPCS out=WORK.ReshapeHCPCS
	(drop=_NAME_ _LABEL_) prefix=Code;
	var HCPCS_CD;
	by BENE_ID PRF_PHYSN_NPI CLM_THRU_DT;
RUN;

PROC SQL;
  DROP TABLE WORK.Carrier_2015a;
  CREATE TABLE WORK.Carrier_2015a AS
  SELECT a.PRF_PHYSN_NPI AS Physician_ID, a.BENE_ID, Count(a.BENE_ID) AS Carrier_Claims, 
	sum(a.LINE_NCH_PMT_AMT) as Carrier_Pay, sum(a.LINE_SBMTD_CHRG_AMT) AS Carrier_Charge,
	a.CLM_THRU_DT AS Claim_Date, 2015 AS Year
  FROM IN027710.BCARLINEK15_R6723 AS a
  GROUP BY a.PRF_PHYSN_NPI, a.BENE_ID, a.CLM_THRU_DT
  ORDER BY a.BENE_ID, a.PRF_PHYSN_NPI, a.CLM_THRU_DT;
QUIT;

PROC SQL;
  DROP TABLE WORK.Carrier_2015;
  CREATE TABLE WORK.Carrier_2015 AS
  SELECT a.*, b.CODE1, b.CODE2, b.CODE3, b.CODE4, b.CODE5, b.CODE6, 
		b.CODE7, b.CODE8, b.CODE9, b.CODE10
  FROM WORK.Carrier_2015a AS a
  LEFT JOIN WORK.ReshapeHCPCS AS b
  	ON a.BENE_ID=b.BENE_ID AND a.Physician_ID=b.PRF_PHYSN_NPI AND a.Claim_Date=b.CLM_THRU_DT;
QUIT;


%LET year_data=2007;

PROC SQL;
	DROP TABLE WORK.Patients;
	CREATE TABLE WORK.Patients AS
	SELECT BENE_ID FROM IMC969SL.INPATIENTSTAYS_&year_data 
		WHERE ORG_NPI_NUM IS NOT NULL AND OP_PHYSN_NPI IS NOT NULL;
QUIT;


PROC SQL;
	DROP TABLE IMC969SL.Carrier_&year_data;
	CREATE TABLE IMC969SL.Carrier_&year_data AS
	SELECT Physician_ID AS Physician_NPI, a.BENE_ID, Carrier_Claims, Carrier_Pay, Carrier_Charge, Claim_Date, Year,
		CODE1, CODE2, CODE3, CODE4, CODE5, CODE6, CODE7, CODE8, CODE9, CODE10
		FROM WORK.Carrier_&year_data AS a
		INNER JOIN WORK.Patients AS b
		ON a.BENE_ID=b.BENE_ID;
QUIT;


%LET year_prior=2007;
%LET year_data=2008;

PROC SQL;
	DROP TABLE WORK.Patients;
	CREATE TABLE WORK.Patients AS
	SELECT BENE_ID FROM IMC969SL.INPATIENTSTAYS_&year_data 
		WHERE ORG_NPI_NUM IS NOT NULL AND OP_PHYSN_NPI IS NOT NULL
		UNION ALL 
		SELECT BENE_ID FROM IMC969SL.INPATIENTSTAYS_&year_prior
		WHERE ORG_NPI_NUM IS NOT NULL AND OP_PHYSN_NPI IS NOT NULL;
QUIT;


PROC SQL;
	DROP TABLE IMC969SL.Carrier_&year_data;
	CREATE TABLE IMC969SL.Carrier_&year_data AS
	SELECT Physician_ID AS Physician_NPI, a.BENE_ID, Carrier_Claims, Carrier_Pay, Carrier_Charge, Claim_Date, Year,
		CODE1, CODE2, CODE3, CODE4, CODE5, CODE6, CODE7, CODE8, CODE9, CODE10
		FROM WORK.Carrier_&year_data AS a
		INNER JOIN WORK.Patients AS b
		ON a.BENE_ID=b.BENE_ID;
QUIT;

%LET year_prior=2008;
%LET year_data=2009;

PROC SQL;
	DROP TABLE WORK.Patients;
	CREATE TABLE WORK.Patients AS
	SELECT BENE_ID FROM IMC969SL.INPATIENTSTAYS_&year_data 
		WHERE ORG_NPI_NUM IS NOT NULL AND OP_PHYSN_NPI IS NOT NULL
		UNION ALL 
		SELECT BENE_ID FROM IMC969SL.INPATIENTSTAYS_&year_prior
		WHERE ORG_NPI_NUM IS NOT NULL AND OP_PHYSN_NPI IS NOT NULL;
QUIT;


PROC SQL;
	DROP TABLE IMC969SL.Carrier_&year_data;
	CREATE TABLE IMC969SL.Carrier_&year_data AS
	SELECT Physician_ID AS Physician_NPI, a.BENE_ID, Carrier_Claims, Carrier_Pay, Carrier_Charge, Claim_Date, Year,
		CODE1, CODE2, CODE3, CODE4, CODE5, CODE6, CODE7, CODE8, CODE9, CODE10
		FROM WORK.Carrier_&year_data AS a
		INNER JOIN WORK.Patients AS b
		ON a.BENE_ID=b.BENE_ID;
QUIT;

%LET year_prior=2009;
%LET year_data=2010;

PROC SQL;
	DROP TABLE WORK.Patients;
	CREATE TABLE WORK.Patients AS
	SELECT BENE_ID FROM IMC969SL.INPATIENTSTAYS_&year_data 
		WHERE ORG_NPI_NUM IS NOT NULL AND OP_PHYSN_NPI IS NOT NULL
		UNION ALL 
		SELECT BENE_ID FROM IMC969SL.INPATIENTSTAYS_&year_prior
		WHERE ORG_NPI_NUM IS NOT NULL AND OP_PHYSN_NPI IS NOT NULL;
QUIT;


PROC SQL;
	DROP TABLE IMC969SL.Carrier_&year_data;
	CREATE TABLE IMC969SL.Carrier_&year_data AS
	SELECT Physician_ID AS Physician_NPI, a.BENE_ID, Carrier_Claims, Carrier_Pay, Carrier_Charge, Claim_Date, Year,
		CODE1, CODE2, CODE3, CODE4, CODE5, CODE6, CODE7, CODE8, CODE9, CODE10
		FROM WORK.Carrier_&year_data AS a
		INNER JOIN WORK.Patients AS b
		ON a.BENE_ID=b.BENE_ID;
QUIT;

%LET year_prior=2010;
%LET year_data=2011;

PROC SQL;
	DROP TABLE WORK.Patients;
	CREATE TABLE WORK.Patients AS
	SELECT BENE_ID FROM IMC969SL.INPATIENTSTAYS_&year_data 
		WHERE ORG_NPI_NUM IS NOT NULL AND OP_PHYSN_NPI IS NOT NULL
		UNION ALL 
		SELECT BENE_ID FROM IMC969SL.INPATIENTSTAYS_&year_prior
		WHERE ORG_NPI_NUM IS NOT NULL AND OP_PHYSN_NPI IS NOT NULL;
QUIT;


PROC SQL;
	DROP TABLE IMC969SL.Carrier_&year_data;
	CREATE TABLE IMC969SL.Carrier_&year_data AS
	SELECT Physician_ID AS Physician_NPI, a.BENE_ID, Carrier_Claims, Carrier_Pay, Carrier_Charge, Claim_Date, Year,
		CODE1, CODE2, CODE3, CODE4, CODE5, CODE6, CODE7, CODE8, CODE9, CODE10
		FROM WORK.Carrier_&year_data AS a
		INNER JOIN WORK.Patients AS b
		ON a.BENE_ID=b.BENE_ID;
QUIT;

%LET year_prior=2011;
%LET year_data=2012;

PROC SQL;
	DROP TABLE WORK.Patients;
	CREATE TABLE WORK.Patients AS
	SELECT BENE_ID FROM IMC969SL.INPATIENTSTAYS_&year_data 
		WHERE ORG_NPI_NUM IS NOT NULL AND OP_PHYSN_NPI IS NOT NULL
		UNION ALL 
		SELECT BENE_ID FROM IMC969SL.INPATIENTSTAYS_&year_prior
		WHERE ORG_NPI_NUM IS NOT NULL AND OP_PHYSN_NPI IS NOT NULL;
QUIT;


PROC SQL;
	DROP TABLE IMC969SL.Carrier_&year_data;
	CREATE TABLE IMC969SL.Carrier_&year_data AS
	SELECT Physician_ID AS Physician_NPI, a.BENE_ID, Carrier_Claims, Carrier_Pay, Carrier_Charge, Claim_Date, Year,
		CODE1, CODE2, CODE3, CODE4, CODE5, CODE6, CODE7, CODE8, CODE9, CODE10
		FROM WORK.Carrier_&year_data AS a
		INNER JOIN WORK.Patients AS b
		ON a.BENE_ID=b.BENE_ID;
QUIT;

%LET year_prior=2012;
%LET year_data=2013;

PROC SQL;
	DROP TABLE WORK.Patients;
	CREATE TABLE WORK.Patients AS
	SELECT BENE_ID FROM IMC969SL.INPATIENTSTAYS_&year_data 
		WHERE ORG_NPI_NUM IS NOT NULL AND OP_PHYSN_NPI IS NOT NULL
		UNION ALL 
		SELECT BENE_ID FROM IMC969SL.INPATIENTSTAYS_&year_prior
		WHERE ORG_NPI_NUM IS NOT NULL AND OP_PHYSN_NPI IS NOT NULL;
QUIT;


PROC SQL;
	DROP TABLE IMC969SL.Carrier_&year_data;
	CREATE TABLE IMC969SL.Carrier_&year_data AS
	SELECT Physician_ID AS Physician_NPI, a.BENE_ID, Carrier_Claims, Carrier_Pay, Carrier_Charge, Claim_Date, Year,
		CODE1, CODE2, CODE3, CODE4, CODE5, CODE6, CODE7, CODE8, CODE9, CODE10
		FROM WORK.Carrier_&year_data AS a
		INNER JOIN WORK.Patients AS b
		ON a.BENE_ID=b.BENE_ID;
QUIT;

%LET year_prior=2013;
%LET year_data=2014;

PROC SQL;
	DROP TABLE WORK.Patients;
	CREATE TABLE WORK.Patients AS
	SELECT BENE_ID FROM IMC969SL.INPATIENTSTAYS_&year_data 
		WHERE ORG_NPI_NUM IS NOT NULL AND OP_PHYSN_NPI IS NOT NULL
		UNION ALL 
		SELECT BENE_ID FROM IMC969SL.INPATIENTSTAYS_&year_prior
		WHERE ORG_NPI_NUM IS NOT NULL AND OP_PHYSN_NPI IS NOT NULL;
QUIT;


PROC SQL;
	DROP TABLE IMC969SL.Carrier_&year_data;
	CREATE TABLE IMC969SL.Carrier_&year_data AS
	SELECT Physician_ID AS Physician_NPI, a.BENE_ID, Carrier_Claims, Carrier_Pay, Carrier_Charge, Claim_Date, Year,
		CODE1, CODE2, CODE3, CODE4, CODE5, CODE6, CODE7, CODE8, CODE9, CODE10
		FROM WORK.Carrier_&year_data AS a
		INNER JOIN WORK.Patients AS b
		ON a.BENE_ID=b.BENE_ID;
QUIT;

%LET year_prior=2014;
%LET year_data=2015;

PROC SQL;
	DROP TABLE WORK.Patients;
	CREATE TABLE WORK.Patients AS
	SELECT BENE_ID FROM IMC969SL.INPATIENTSTAYS_&year_data 
		WHERE ORG_NPI_NUM IS NOT NULL AND OP_PHYSN_NPI IS NOT NULL
		UNION ALL 
		SELECT BENE_ID FROM IMC969SL.INPATIENTSTAYS_&year_prior
		WHERE ORG_NPI_NUM IS NOT NULL AND OP_PHYSN_NPI IS NOT NULL;
QUIT;


PROC SQL;
	DROP TABLE IMC969SL.Carrier_&year_data;
	CREATE TABLE IMC969SL.Carrier_&year_data AS
	SELECT Physician_ID AS Physician_NPI, a.BENE_ID, Carrier_Claims, Carrier_Pay, Carrier_Charge, Claim_Date, Year,
		CODE1, CODE2, CODE3, CODE4, CODE5, CODE6, CODE7, CODE8, CODE9, CODE10
		FROM WORK.Carrier_&year_data AS a
		INNER JOIN WORK.Patients AS b
		ON a.BENE_ID=b.BENE_ID;
QUIT;



/* Sum by physician and hcpcs codes */
PROC SQL;
	DROP TABLE IMC969SL.HCPCS_2007;
	CREATE TABLE IMC969SL.HCPCS_2007 AS
	SELECT PRF_PHYSN_NPI AS Physician_ID, Count(BENE_ID) AS Carrier_Claims, 
		sum(LINE_NCH_PMT_AMT) as Carrier_Pay, sum(LINE_SBMTD_CHRG_AMT) AS Carrier_Charge,
		HCPCS_CD, 2007 AS Year
  	FROM IN027710.BCARLINEK07_R6723
  	WHERE PRF_PHYSN_NPI IS NOT NULL AND HCPCS_CD IS NOT NULL
  	GROUP BY PRF_PHYSN_NPI, HCPCS_CD;
QUIT;

PROC SQL;
	DROP TABLE IMC969SL.HCPCS_2008;
	CREATE TABLE IMC969SL.HCPCS_2008 AS
	SELECT PRF_PHYSN_NPI AS Physician_ID, Count(BENE_ID) AS Carrier_Claims, 
		sum(LINE_NCH_PMT_AMT) as Carrier_Pay, sum(LINE_SBMTD_CHRG_AMT) AS Carrier_Charge,
		HCPCS_CD, 2008 AS Year
	FROM IN027710.BCARLINEK08_R6723
  	WHERE PRF_PHYSN_NPI IS NOT NULL AND HCPCS_CD IS NOT NULL
  	GROUP BY PRF_PHYSN_NPI, HCPCS_CD;
QUIT;


PROC SQL;
	DROP TABLE IMC969SL.HCPCS_2009;
	CREATE TABLE IMC969SL.HCPCS_2009 AS
	SELECT PRF_PHYSN_NPI AS Physician_ID, Count(BENE_ID) AS Carrier_Claims, 
		sum(LINE_NCH_PMT_AMT) as Carrier_Pay, sum(LINE_SBMTD_CHRG_AMT) AS Carrier_Charge,
		HCPCS_CD, 2009 AS Year
	FROM IN027710.BCARLINEJ09_R4585
  	WHERE PRF_PHYSN_NPI IS NOT NULL AND HCPCS_CD IS NOT NULL
  	GROUP BY PRF_PHYSN_NPI, HCPCS_CD;
QUIT;

PROC SQL;
	DROP TABLE IMC969SL.HCPCS_2010;
	CREATE TABLE IMC969SL.HCPCS_2010 AS
	SELECT PRF_PHYSN_NPI AS Physician_ID, Count(BENE_ID) AS Carrier_Claims, 
		sum(LINE_NCH_PMT_AMT) as Carrier_Pay, sum(LINE_SBMTD_CHRG_AMT) AS Carrier_Charge,
		HCPCS_CD, 2010 AS Year
  	FROM IN027710.BCARLINEJ10_R4585
  	WHERE PRF_PHYSN_NPI IS NOT NULL AND HCPCS_CD IS NOT NULL
  	GROUP BY PRF_PHYSN_NPI, HCPCS_CD;
QUIT;


PROC SQL;
	DROP TABLE IMC969SL.HCPCS_2011;
	CREATE TABLE IMC969SL.HCPCS_2011 AS
	SELECT PRF_PHYSN_NPI AS Physician_ID, Count(BENE_ID) AS Carrier_Claims, 
		sum(LINE_NCH_PMT_AMT) as Carrier_Pay, sum(LINE_SBMTD_CHRG_AMT) AS Carrier_Charge,
		HCPCS_CD, 2011 AS Year
  	FROM IN027710.BCARLINEJ11_R4585
  	WHERE PRF_PHYSN_NPI IS NOT NULL AND HCPCS_CD IS NOT NULL
  	GROUP BY PRF_PHYSN_NPI, HCPCS_CD;
QUIT;


PROC SQL;
	DROP TABLE IMC969SL.HCPCS_2012;
	CREATE TABLE IMC969SL.HCPCS_2012 AS
	SELECT PRF_PHYSN_NPI AS Physician_ID, Count(BENE_ID) AS Carrier_Claims, 
		sum(LINE_NCH_PMT_AMT) as Carrier_Pay, sum(LINE_SBMTD_CHRG_AMT) AS Carrier_Charge,
		HCPCS_CD, 2012 AS Year
  	FROM IN027710.BCARLINEK12_R6723
  	WHERE PRF_PHYSN_NPI IS NOT NULL AND HCPCS_CD IS NOT NULL
  	GROUP BY PRF_PHYSN_NPI, HCPCS_CD;
QUIT;


PROC SQL;
	DROP TABLE IMC969SL.HCPCS_2013;
	CREATE TABLE IMC969SL.HCPCS_2013 AS
	SELECT PRF_PHYSN_NPI AS Physician_ID, Count(BENE_ID) AS Carrier_Claims, 
		sum(LINE_NCH_PMT_AMT) as Carrier_Pay, sum(LINE_SBMTD_CHRG_AMT) AS Carrier_Charge,
		HCPCS_CD, 2013 AS Year
  	FROM IN027710.BCARLINEK13_R6723
  	WHERE PRF_PHYSN_NPI IS NOT NULL AND HCPCS_CD IS NOT NULL
  	GROUP BY PRF_PHYSN_NPI, HCPCS_CD;
QUIT;


PROC SQL;
	DROP TABLE IMC969SL.HCPCS_2014;
	CREATE TABLE IMC969SL.HCPCS_2014 AS
	SELECT PRF_PHYSN_NPI AS Physician_ID, Count(BENE_ID) AS Carrier_Claims, 
		sum(LINE_NCH_PMT_AMT) as Carrier_Pay, sum(LINE_SBMTD_CHRG_AMT) AS Carrier_Charge,
		HCPCS_CD, 2014 AS Year
  	FROM IN027710.BCARLINEK14_R6723
  	WHERE PRF_PHYSN_NPI IS NOT NULL AND HCPCS_CD IS NOT NULL
  	GROUP BY PRF_PHYSN_NPI, HCPCS_CD;
QUIT;


PROC SQL;
	DROP TABLE IMC969SL.HCPCS_2015;
	CREATE TABLE IMC969SL.HCPCS_2015 AS
	SELECT PRF_PHYSN_NPI AS Physician_ID, Count(BENE_ID) AS Carrier_Claims, 
		sum(LINE_NCH_PMT_AMT) as Carrier_Pay, sum(LINE_SBMTD_CHRG_AMT) AS Carrier_Charge,
		HCPCS_CD, 2015 AS Year
  	FROM IN027710.BCARLINEK15_R6723
  	WHERE PRF_PHYSN_NPI IS NOT NULL AND HCPCS_CD IS NOT NULL
  	GROUP BY PRF_PHYSN_NPI, HCPCS_CD;
QUIT;