/* ------------------------------------------------------------ */
/* TITLE:		 Find Outpatient Stays initiated by physician   */
/* 				 referral, clinic referral, or HMO referral  	*/
/* AUTHOR:		 Ian McCarthy									*/
/* 				 Emory University								*/
/* DATE CREATED: 2/20/2017										*/
/* DATE EDITED:  3/2/2018										*/
/* CODE FILE ORDER: 1 of XX  									*/
/* NOTES:														*/
/*   BENE_CC  Master beneficiary summary file 					*/
/*   MCBSxxxx Medicare Current Beneficiary Survey (Year xxxx) 	*/
/*   MCBSXWLK MCBS Crosswalk 									*/
/*   RIFSxxxx Out/Inpatient and Carrier claims (Year xxxx)  	*/
/*   Medpar   Inpatient claims  								*/
/*   -- File outputs the following tables to IMC969SL:			*/
/*		InpatientStays_2007-2015  								*/
/* ------------------------------------------------------------ */

/* Create Table of Outpatient Stays for 2007 */
DATA WORK.OutpatientStays;
	SET	RIF2007.OUTPATIENT_CLAIMS_01
  		RIF2007.OUTPATIENT_CLAIMS_02
		RIF2007.OUTPATIENT_CLAIMS_03
		RIF2007.OUTPATIENT_CLAIMS_04
		RIF2007.OUTPATIENT_CLAIMS_05
		RIF2007.OUTPATIENT_CLAIMS_06
		RIF2007.OUTPATIENT_CLAIMS_07
		RIF2007.OUTPATIENT_CLAIMS_08
		RIF2007.OUTPATIENT_CLAIMS_09
		RIF2007.OUTPATIENT_CLAIMS_10
		RIF2007.OUTPATIENT_CLAIMS_11
		RIF2007.OUTPATIENT_CLAIMS_12;
RUN;

DATA WORK.OutpatientHCPCS;
	SET	RIF2007.OUTPATIENT_REVENUE_01
  		RIF2007.OUTPATIENT_REVENUE_02
		RIF2007.OUTPATIENT_REVENUE_03
		RIF2007.OUTPATIENT_REVENUE_04
		RIF2007.OUTPATIENT_REVENUE_05
		RIF2007.OUTPATIENT_REVENUE_06
		RIF2007.OUTPATIENT_REVENUE_07
		RIF2007.OUTPATIENT_REVENUE_08
		RIF2007.OUTPATIENT_REVENUE_09
		RIF2007.OUTPATIENT_REVENUE_10
		RIF2007.OUTPATIENT_REVENUE_11
		RIF2007.OUTPATIENT_REVENUE_12;
RUN;

PROC SQL;
	DROP TABLE WORK.HCPCS;
	CREATE TABLE WORK.HCPCS AS
	SELECT DISTINCT BENE_ID, CLM_ID, HCPCS_CD
	FROM WORK.OutpatientHCPCS
	WHERE HCPCS_CD IS NOT NULL;
QUIT;

PROC SQL;
	DROP TABLE IMC969SL.HCPCS_OP_2007;
	CREATE TABLE IMC969SL.HCPCS_OP_2007 AS
	SELECT HCPCS_CD, Count(CLM_ID) AS OP_Count, 2007 AS Year
	FROM WORK.HCPCS
	GROUP BY HCPCS_CD;
QUIT;


PROC TRANSPOSE data=WORK.HCPCS out=WORK.ReshapeHCPCS
	(drop=_NAME_ _LABEL_) prefix=Code;
	var HCPCS_CD;
	by BENE_ID CLM_ID;
RUN;


PROC SQL;
	DROP TABLE IMC969SL.OutpatientStays_2007;
	CREATE TABLE IMC969SL.OutpatientStays_2007 AS
	SELECT a.BENE_ID, a.CLM_ID, a.CLM_FROM_DT, a.CLM_THRU_DT, a.PRVDR_NUM, 
		CASE
			WHEN a.ORG_NPI_NUM NE '' AND a.ORG_NPI_NUM NE '0000000000' THEN a.ORG_NPI_NUM
			WHEN a.ORG_NPI_NUM='' OR a.ORG_NPI_NUM='0000000000' THEN b.NPI
		ELSE ''
		END AS ORG_NPI_NUM,
		a.OP_PHYSN_UPIN,
		CASE 
			WHEN a.OP_PHYSN_NPI NE '' AND a.OP_PHYSN_NPI NE '0000000000' THEN a.OP_PHYSN_NPI
			WHEN a.OP_PHYSN_NPI='' OR a.OP_PHYSN_NPI='0000000000' THEN c.NPI
		ELSE ''
		END AS OP_PHYSN_NPI,
		a.CLM_PMT_AMT, a.CLM_TOT_CHRG_AMT, 
		a.PRNCPAL_DGNS_CD, a.ICD_DGNS_CD1, a.ICD_DGNS_CD2, a.ICD_DGNS_CD3, a.ICD_DGNS_CD4, a.ICD_DGNS_CD5, 
		a.ICD_DGNS_CD6, a.ICD_DGNS_CD7, a.ICD_DGNS_CD8, a.ICD_DGNS_CD9, a.ICD_DGNS_CD10,
		a.ICD_PRCDR_CD1, a.ICD_PRCDR_CD2, d.CODE1, d.CODE2, d.CODE3, d.CODE4, d.CODE5, d.CODE6, 
		d.CODE7, d.CODE8, d.CODE9, d.CODE10
	FROM WORK.OutpatientStays AS a
	LEFT JOIN IMC969SL.PRVN_NPI_Merge_2007 AS b
		ON a.PRVDR_NUM=b.PRVDR_NUM
	LEFT JOIN IMC969SL.UPIN_NPI_Merge_2007 AS c
		ON a.OP_PHYSN_UPIN=c.OP_PHYSN_UPIN
	LEFT JOIN WORK.ReshapeHCPCS AS d
		ON a.CLM_ID=d.CLM_ID AND a.BENE_ID=d.BENE_ID;
QUIT;



/* Create Table of Outpatient Stays for 2008 */
DATA WORK.OutpatientStays;
	SET	RIF2008.OUTPATIENT_CLAIMS_01
  		RIF2008.OUTPATIENT_CLAIMS_02
		RIF2008.OUTPATIENT_CLAIMS_03
		RIF2008.OUTPATIENT_CLAIMS_04
		RIF2008.OUTPATIENT_CLAIMS_05
		RIF2008.OUTPATIENT_CLAIMS_06
		RIF2008.OUTPATIENT_CLAIMS_07
		RIF2008.OUTPATIENT_CLAIMS_08
		RIF2008.OUTPATIENT_CLAIMS_09
		RIF2008.OUTPATIENT_CLAIMS_10
		RIF2008.OUTPATIENT_CLAIMS_11
		RIF2008.OUTPATIENT_CLAIMS_12;
RUN;

DATA WORK.OutpatientHCPCS;
	SET	RIF2008.OUTPATIENT_REVENUE_01
  		RIF2008.OUTPATIENT_REVENUE_02
		RIF2008.OUTPATIENT_REVENUE_03
		RIF2008.OUTPATIENT_REVENUE_04
		RIF2008.OUTPATIENT_REVENUE_05
		RIF2008.OUTPATIENT_REVENUE_06
		RIF2008.OUTPATIENT_REVENUE_07
		RIF2008.OUTPATIENT_REVENUE_08
		RIF2008.OUTPATIENT_REVENUE_09
		RIF2008.OUTPATIENT_REVENUE_10
		RIF2008.OUTPATIENT_REVENUE_11
		RIF2008.OUTPATIENT_REVENUE_12;
RUN;

PROC SQL;
	DROP TABLE WORK.HCPCS;
	CREATE TABLE WORK.HCPCS AS
	SELECT DISTINCT BENE_ID, CLM_ID, HCPCS_CD
	FROM WORK.OutpatientHCPCS
	WHERE HCPCS_CD IS NOT NULL;
QUIT;

PROC SQL;
	DROP TABLE IMC969SL.HCPCS_OP_2008;
	CREATE TABLE IMC969SL.HCPCS_OP_2008 AS
	SELECT HCPCS_CD, Count(CLM_ID) AS OP_Count, 2008 AS Year
	FROM WORK.HCPCS
	GROUP BY HCPCS_CD;
QUIT;


PROC TRANSPOSE data=WORK.HCPCS out=WORK.ReshapeHCPCS
	(drop=_NAME_ _LABEL_) prefix=Code;
	var HCPCS_CD;
	by BENE_ID CLM_ID;
RUN;


PROC SQL;
	DROP TABLE IMC969SL.OutpatientStays_2008;
	CREATE TABLE IMC969SL.OutpatientStays_2008 AS
	SELECT a.BENE_ID, a.CLM_ID, a.CLM_FROM_DT, a.CLM_THRU_DT, a.PRVDR_NUM, 
		CASE
			WHEN a.ORG_NPI_NUM NE '' AND a.ORG_NPI_NUM NE '0000000000' THEN a.ORG_NPI_NUM
			WHEN a.ORG_NPI_NUM='' OR a.ORG_NPI_NUM='0000000000' THEN b.NPI
		ELSE ''
		END AS ORG_NPI_NUM,
		a.OP_PHYSN_UPIN,
		CASE 
			WHEN a.OP_PHYSN_NPI NE '' AND a.OP_PHYSN_NPI NE '0000000000' THEN a.OP_PHYSN_NPI
			WHEN a.OP_PHYSN_NPI='' OR a.OP_PHYSN_NPI='0000000000' THEN c.NPI
		ELSE ''
		END AS OP_PHYSN_NPI,
		a.CLM_PMT_AMT, a.CLM_TOT_CHRG_AMT, 
		a.PRNCPAL_DGNS_CD, a.ICD_DGNS_CD1, a.ICD_DGNS_CD2, a.ICD_DGNS_CD3, a.ICD_DGNS_CD4, a.ICD_DGNS_CD5, 
		a.ICD_DGNS_CD6, a.ICD_DGNS_CD7, a.ICD_DGNS_CD8, a.ICD_DGNS_CD9, a.ICD_DGNS_CD10,
		a.ICD_PRCDR_CD1, a.ICD_PRCDR_CD2, d.CODE1, d.CODE2, d.CODE3, d.CODE4, d.CODE5, d.CODE6, 
		d.CODE7, d.CODE8, d.CODE9, d.CODE10
	FROM WORK.OutpatientStays AS a
	LEFT JOIN IMC969SL.PRVN_NPI_Merge_2008 AS b
		ON a.PRVDR_NUM=b.PRVDR_NUM
	LEFT JOIN IMC969SL.UPIN_NPI_Merge_2008 AS c
		ON a.OP_PHYSN_UPIN=c.OP_PHYSN_UPIN
	LEFT JOIN WORK.ReshapeHCPCS AS d
		ON a.CLM_ID=d.CLM_ID AND a.BENE_ID=d.BENE_ID;
QUIT;



/* Create Table of Outpatient Stays for 2009 */
DATA WORK.OutpatientStays;
	SET	RIF2009.OUTPATIENT_CLAIMS_01
  		RIF2009.OUTPATIENT_CLAIMS_02
		RIF2009.OUTPATIENT_CLAIMS_03
		RIF2009.OUTPATIENT_CLAIMS_04
		RIF2009.OUTPATIENT_CLAIMS_05
		RIF2009.OUTPATIENT_CLAIMS_06
		RIF2009.OUTPATIENT_CLAIMS_07
		RIF2009.OUTPATIENT_CLAIMS_08
		RIF2009.OUTPATIENT_CLAIMS_09
		RIF2009.OUTPATIENT_CLAIMS_10
		RIF2009.OUTPATIENT_CLAIMS_11
		RIF2009.OUTPATIENT_CLAIMS_12;
RUN;

DATA WORK.OutpatientHCPCS;
	SET	RIF2009.OUTPATIENT_REVENUE_01
  		RIF2009.OUTPATIENT_REVENUE_02
		RIF2009.OUTPATIENT_REVENUE_03
		RIF2009.OUTPATIENT_REVENUE_04
		RIF2009.OUTPATIENT_REVENUE_05
		RIF2009.OUTPATIENT_REVENUE_06
		RIF2009.OUTPATIENT_REVENUE_07
		RIF2009.OUTPATIENT_REVENUE_08
		RIF2009.OUTPATIENT_REVENUE_09
		RIF2009.OUTPATIENT_REVENUE_10
		RIF2009.OUTPATIENT_REVENUE_11
		RIF2009.OUTPATIENT_REVENUE_12;
RUN;

PROC SQL;
	DROP TABLE WORK.HCPCS;
	CREATE TABLE WORK.HCPCS AS
	SELECT DISTINCT BENE_ID, CLM_ID, HCPCS_CD
	FROM WORK.OutpatientHCPCS
	WHERE HCPCS_CD IS NOT NULL;
QUIT;

PROC SQL;
	DROP TABLE IMC969SL.HCPCS_OP_2009;
	CREATE TABLE IMC969SL.HCPCS_OP_2009 AS
	SELECT HCPCS_CD, Count(CLM_ID) AS OP_Count, 2009 AS Year
	FROM WORK.HCPCS
	GROUP BY HCPCS_CD;
QUIT;


PROC TRANSPOSE data=WORK.HCPCS out=WORK.ReshapeHCPCS
	(drop=_NAME_ _LABEL_) prefix=Code;
	var HCPCS_CD;
	by BENE_ID CLM_ID;
RUN;


PROC SQL;
	DROP TABLE IMC969SL.OutpatientStays_2009;
	CREATE TABLE IMC969SL.OutpatientStays_2009 AS
	SELECT a.BENE_ID, a.CLM_ID, a.CLM_FROM_DT, a.CLM_THRU_DT, a.PRVDR_NUM, 
		a.ORG_NPI_NUM, a.OP_PHYSN_NPI,
		a.CLM_PMT_AMT, a.CLM_TOT_CHRG_AMT, 
		a.PRNCPAL_DGNS_CD, a.ICD_DGNS_CD1, a.ICD_DGNS_CD2, a.ICD_DGNS_CD3, a.ICD_DGNS_CD4, a.ICD_DGNS_CD5, 
		a.ICD_DGNS_CD6, a.ICD_DGNS_CD7, a.ICD_DGNS_CD8, a.ICD_DGNS_CD9, a.ICD_DGNS_CD10,
		a.ICD_PRCDR_CD1, a.ICD_PRCDR_CD2, b.CODE1, b.CODE2, b.CODE3, b.CODE4, b.CODE5, b.CODE6, 
		b.CODE7, b.CODE8, b.CODE9, b.CODE10 
	FROM WORK.OutpatientStays AS a
	LEFT JOIN WORK.ReshapeHCPCS AS b
		ON a.CLM_ID=b.CLM_ID AND a.BENE_ID=b.BENE_ID;
QUIT;


/* Create Table of Outpatient Stays for 2010 */
DATA WORK.OutpatientStays;
	SET	RIF2010.OUTPATIENT_CLAIMS_01
  		RIF2010.OUTPATIENT_CLAIMS_02
		RIF2010.OUTPATIENT_CLAIMS_03
		RIF2010.OUTPATIENT_CLAIMS_04
		RIF2010.OUTPATIENT_CLAIMS_05
		RIF2010.OUTPATIENT_CLAIMS_06
		RIF2010.OUTPATIENT_CLAIMS_07
		RIF2010.OUTPATIENT_CLAIMS_08
		RIF2010.OUTPATIENT_CLAIMS_09
		RIF2010.OUTPATIENT_CLAIMS_10
		RIF2010.OUTPATIENT_CLAIMS_11
		RIF2010.OUTPATIENT_CLAIMS_12;
RUN;

DATA WORK.OutpatientHCPCS;
	SET	RIF2010.OUTPATIENT_REVENUE_01
  		RIF2010.OUTPATIENT_REVENUE_02
		RIF2010.OUTPATIENT_REVENUE_03
		RIF2010.OUTPATIENT_REVENUE_04
		RIF2010.OUTPATIENT_REVENUE_05
		RIF2010.OUTPATIENT_REVENUE_06
		RIF2010.OUTPATIENT_REVENUE_07
		RIF2010.OUTPATIENT_REVENUE_08
		RIF2010.OUTPATIENT_REVENUE_09
		RIF2010.OUTPATIENT_REVENUE_10
		RIF2010.OUTPATIENT_REVENUE_11
		RIF2010.OUTPATIENT_REVENUE_12;
RUN;

PROC SQL;
	DROP TABLE WORK.HCPCS;
	CREATE TABLE WORK.HCPCS AS
	SELECT DISTINCT BENE_ID, CLM_ID, HCPCS_CD
	FROM WORK.OutpatientHCPCS
	WHERE HCPCS_CD IS NOT NULL;
QUIT;

PROC SQL;
	DROP TABLE IMC969SL.HCPCS_OP_2010;
	CREATE TABLE IMC969SL.HCPCS_OP_2010 AS
	SELECT HCPCS_CD, Count(CLM_ID) AS OP_Count, 2010 AS Year
	FROM WORK.HCPCS
	GROUP BY HCPCS_CD;
QUIT;


PROC TRANSPOSE data=WORK.HCPCS out=WORK.ReshapeHCPCS
	(drop=_NAME_ _LABEL_) prefix=Code;
	var HCPCS_CD;
	by BENE_ID CLM_ID;
RUN;


PROC SQL;
	DROP TABLE IMC969SL.OutpatientStays_2010;
	CREATE TABLE IMC969SL.OutpatientStays_2010 AS
	SELECT a.BENE_ID, a.CLM_ID, a.CLM_FROM_DT, a.CLM_THRU_DT, a.PRVDR_NUM, 
		a.ORG_NPI_NUM, a.OP_PHYSN_NPI,
		a.CLM_PMT_AMT, a.CLM_TOT_CHRG_AMT, 
		a.PRNCPAL_DGNS_CD, a.ICD_DGNS_CD1, a.ICD_DGNS_CD2, a.ICD_DGNS_CD3, a.ICD_DGNS_CD4, a.ICD_DGNS_CD5, 
		a.ICD_DGNS_CD6, a.ICD_DGNS_CD7, a.ICD_DGNS_CD8, a.ICD_DGNS_CD9, a.ICD_DGNS_CD10,
		a.ICD_PRCDR_CD1, a.ICD_PRCDR_CD2, b.CODE1, b.CODE2, b.CODE3, b.CODE4, b.CODE5, b.CODE6, 
		b.CODE7, b.CODE8, b.CODE9, b.CODE10 
	FROM WORK.OutpatientStays AS a
	LEFT JOIN WORK.ReshapeHCPCS AS b
		ON a.CLM_ID=b.CLM_ID AND a.BENE_ID=b.BENE_ID;
QUIT;



/* Create Table of Outpatient Stays for 2011 */
DATA WORK.OutpatientStays;
	SET	RIF2011.OUTPATIENT_CLAIMS_01
  		RIF2011.OUTPATIENT_CLAIMS_02
		RIF2011.OUTPATIENT_CLAIMS_03
		RIF2011.OUTPATIENT_CLAIMS_04
		RIF2011.OUTPATIENT_CLAIMS_05
		RIF2011.OUTPATIENT_CLAIMS_06
		RIF2011.OUTPATIENT_CLAIMS_07
		RIF2011.OUTPATIENT_CLAIMS_08
		RIF2011.OUTPATIENT_CLAIMS_09
		RIF2011.OUTPATIENT_CLAIMS_10
		RIF2011.OUTPATIENT_CLAIMS_11
		RIF2011.OUTPATIENT_CLAIMS_12;
RUN;

DATA WORK.OutpatientHCPCS;
	SET	RIF2011.OUTPATIENT_REVENUE_01
  		RIF2011.OUTPATIENT_REVENUE_02
		RIF2011.OUTPATIENT_REVENUE_03
		RIF2011.OUTPATIENT_REVENUE_04
		RIF2011.OUTPATIENT_REVENUE_05
		RIF2011.OUTPATIENT_REVENUE_06
		RIF2011.OUTPATIENT_REVENUE_07
		RIF2011.OUTPATIENT_REVENUE_08
		RIF2011.OUTPATIENT_REVENUE_09
		RIF2011.OUTPATIENT_REVENUE_10
		RIF2011.OUTPATIENT_REVENUE_11
		RIF2011.OUTPATIENT_REVENUE_12;
RUN;

PROC SQL;
	DROP TABLE WORK.HCPCS;
	CREATE TABLE WORK.HCPCS AS
	SELECT DISTINCT BENE_ID, CLM_ID, HCPCS_CD
	FROM WORK.OutpatientHCPCS
	WHERE HCPCS_CD IS NOT NULL;
QUIT;

PROC SQL;
	DROP TABLE IMC969SL.HCPCS_OP_2011;
	CREATE TABLE IMC969SL.HCPCS_OP_2011 AS
	SELECT HCPCS_CD, Count(CLM_ID) AS OP_Count, 2011 AS Year
	FROM WORK.HCPCS
	GROUP BY HCPCS_CD;
QUIT;



PROC TRANSPOSE data=WORK.HCPCS out=WORK.ReshapeHCPCS
	(drop=_NAME_ _LABEL_) prefix=Code;
	var HCPCS_CD;
	by BENE_ID CLM_ID;
RUN;


PROC SQL;
	DROP TABLE IMC969SL.OutpatientStays_2011;
	CREATE TABLE IMC969SL.OutpatientStays_2011 AS
	SELECT a.BENE_ID, a.CLM_ID, a.CLM_FROM_DT, a.CLM_THRU_DT, a.PRVDR_NUM, 
		a.ORG_NPI_NUM, a.OP_PHYSN_NPI,
		a.CLM_PMT_AMT, a.CLM_TOT_CHRG_AMT, 
		a.PRNCPAL_DGNS_CD, a.ICD_DGNS_CD1, a.ICD_DGNS_CD2, a.ICD_DGNS_CD3, a.ICD_DGNS_CD4, a.ICD_DGNS_CD5, 
		a.ICD_DGNS_CD6, a.ICD_DGNS_CD7, a.ICD_DGNS_CD8, a.ICD_DGNS_CD9, a.ICD_DGNS_CD10,
		a.ICD_PRCDR_CD1, a.ICD_PRCDR_CD2, b.CODE1, b.CODE2, b.CODE3, b.CODE4, b.CODE5, b.CODE6, 
		b.CODE7, b.CODE8, b.CODE9, b.CODE10 
	FROM WORK.OutpatientStays AS a
	LEFT JOIN WORK.ReshapeHCPCS AS b
		ON a.CLM_ID=b.CLM_ID AND a.BENE_ID=b.BENE_ID;
QUIT;


/* Create Table of Outpatient Stays for 2012 */
DATA WORK.OutpatientStays;
	SET	RIF2012.OUTPATIENT_CLAIMS_01
  		RIF2012.OUTPATIENT_CLAIMS_02
		RIF2012.OUTPATIENT_CLAIMS_03
		RIF2012.OUTPATIENT_CLAIMS_04
		RIF2012.OUTPATIENT_CLAIMS_05
		RIF2012.OUTPATIENT_CLAIMS_06
		RIF2012.OUTPATIENT_CLAIMS_07
		RIF2012.OUTPATIENT_CLAIMS_08
		RIF2012.OUTPATIENT_CLAIMS_09
		RIF2012.OUTPATIENT_CLAIMS_10
		RIF2012.OUTPATIENT_CLAIMS_11
		RIF2012.OUTPATIENT_CLAIMS_12;
RUN;

DATA WORK.OutpatientHCPCS;
	SET	RIF2012.OUTPATIENT_REVENUE_01
  		RIF2012.OUTPATIENT_REVENUE_02
		RIF2012.OUTPATIENT_REVENUE_03
		RIF2012.OUTPATIENT_REVENUE_04
		RIF2012.OUTPATIENT_REVENUE_05
		RIF2012.OUTPATIENT_REVENUE_06
		RIF2012.OUTPATIENT_REVENUE_07
		RIF2012.OUTPATIENT_REVENUE_08
		RIF2012.OUTPATIENT_REVENUE_09
		RIF2012.OUTPATIENT_REVENUE_10
		RIF2012.OUTPATIENT_REVENUE_11
		RIF2012.OUTPATIENT_REVENUE_12;
RUN;

PROC SQL;
	DROP TABLE WORK.HCPCS;
	CREATE TABLE WORK.HCPCS AS
	SELECT DISTINCT BENE_ID, CLM_ID, HCPCS_CD
	FROM WORK.OutpatientHCPCS
	WHERE HCPCS_CD IS NOT NULL;
QUIT;

PROC SQL;
	DROP TABLE IMC969SL.HCPCS_OP_2012;
	CREATE TABLE IMC969SL.HCPCS_OP_2012 AS
	SELECT HCPCS_CD, Count(CLM_ID) AS OP_Count, 2012 AS Year
	FROM WORK.HCPCS
	GROUP BY HCPCS_CD;
QUIT;

PROC TRANSPOSE data=WORK.HCPCS out=WORK.ReshapeHCPCS
	(drop=_NAME_ _LABEL_) prefix=Code;
	var HCPCS_CD;
	by BENE_ID CLM_ID;
RUN;


PROC SQL;
	DROP TABLE IMC969SL.OutpatientStays_2012;
	CREATE TABLE IMC969SL.OutpatientStays_2012 AS
	SELECT a.BENE_ID, a.CLM_ID, a.CLM_FROM_DT, a.CLM_THRU_DT, a.PRVDR_NUM, 
		a.ORG_NPI_NUM, a.OP_PHYSN_NPI,
		a.CLM_PMT_AMT, a.CLM_TOT_CHRG_AMT, 
		a.PRNCPAL_DGNS_CD, a.ICD_DGNS_CD1, a.ICD_DGNS_CD2, a.ICD_DGNS_CD3, a.ICD_DGNS_CD4, a.ICD_DGNS_CD5, 
		a.ICD_DGNS_CD6, a.ICD_DGNS_CD7, a.ICD_DGNS_CD8, a.ICD_DGNS_CD9, a.ICD_DGNS_CD10,
		a.ICD_PRCDR_CD1, a.ICD_PRCDR_CD2, b.CODE1, b.CODE2, b.CODE3, b.CODE4, b.CODE5, b.CODE6, 
		b.CODE7, b.CODE8, b.CODE9, b.CODE10 
	FROM WORK.OutpatientStays AS a
	LEFT JOIN WORK.ReshapeHCPCS AS b
		ON a.CLM_ID=b.CLM_ID AND a.BENE_ID=b.BENE_ID;
QUIT;


/* Create Table of Outpatient Stays for 2013 */
DATA WORK.OutpatientStays;
	SET	RIF2013.OUTPATIENT_CLAIMS_01
  		RIF2013.OUTPATIENT_CLAIMS_02
		RIF2013.OUTPATIENT_CLAIMS_03
		RIF2013.OUTPATIENT_CLAIMS_04
		RIF2013.OUTPATIENT_CLAIMS_05
		RIF2013.OUTPATIENT_CLAIMS_06
		RIF2013.OUTPATIENT_CLAIMS_07
		RIF2013.OUTPATIENT_CLAIMS_08
		RIF2013.OUTPATIENT_CLAIMS_09
		RIF2013.OUTPATIENT_CLAIMS_10
		RIF2013.OUTPATIENT_CLAIMS_11
		RIF2013.OUTPATIENT_CLAIMS_12;
RUN;

DATA WORK.OutpatientHCPCS;
	SET	RIF2013.OUTPATIENT_REVENUE_01
  		RIF2013.OUTPATIENT_REVENUE_02
		RIF2013.OUTPATIENT_REVENUE_03
		RIF2013.OUTPATIENT_REVENUE_04
		RIF2013.OUTPATIENT_REVENUE_05
		RIF2013.OUTPATIENT_REVENUE_06
		RIF2013.OUTPATIENT_REVENUE_07
		RIF2013.OUTPATIENT_REVENUE_08
		RIF2013.OUTPATIENT_REVENUE_09
		RIF2013.OUTPATIENT_REVENUE_10
		RIF2013.OUTPATIENT_REVENUE_11
		RIF2013.OUTPATIENT_REVENUE_12;
RUN;

PROC SQL;
	DROP TABLE WORK.HCPCS;
	CREATE TABLE WORK.HCPCS AS
	SELECT DISTINCT BENE_ID, CLM_ID, HCPCS_CD
	FROM WORK.OutpatientHCPCS
	WHERE HCPCS_CD IS NOT NULL;
QUIT;

PROC SQL;
	DROP TABLE IMC969SL.HCPCS_OP_2013;
	CREATE TABLE IMC969SL.HCPCS_OP_2013 AS
	SELECT HCPCS_CD, Count(CLM_ID) AS OP_Count, 2013 AS Year
	FROM WORK.HCPCS
	GROUP BY HCPCS_CD;
QUIT;


PROC TRANSPOSE data=WORK.HCPCS out=WORK.ReshapeHCPCS
	(drop=_NAME_ _LABEL_) prefix=Code;
	var HCPCS_CD;
	by BENE_ID CLM_ID;
RUN;


PROC SQL;
	DROP TABLE IMC969SL.OutpatientStays_2013;
	CREATE TABLE IMC969SL.OutpatientStays_2013 AS
	SELECT a.BENE_ID, a.CLM_ID, a.CLM_FROM_DT, a.CLM_THRU_DT, a.PRVDR_NUM, 
		a.ORG_NPI_NUM, a.OP_PHYSN_NPI,
		a.CLM_PMT_AMT, a.CLM_TOT_CHRG_AMT, 
		a.PRNCPAL_DGNS_CD, a.ICD_DGNS_CD1, a.ICD_DGNS_CD2, a.ICD_DGNS_CD3, a.ICD_DGNS_CD4, a.ICD_DGNS_CD5, 
		a.ICD_DGNS_CD6, a.ICD_DGNS_CD7, a.ICD_DGNS_CD8, a.ICD_DGNS_CD9, a.ICD_DGNS_CD10,
		a.ICD_PRCDR_CD1, a.ICD_PRCDR_CD2, b.CODE1, b.CODE2, b.CODE3, b.CODE4, b.CODE5, b.CODE6, 
		b.CODE7, b.CODE8, b.CODE9, b.CODE10 
	FROM WORK.OutpatientStays AS a
	LEFT JOIN WORK.ReshapeHCPCS AS b
		ON a.CLM_ID=b.CLM_ID AND a.BENE_ID=b.BENE_ID;
QUIT;


/* Create Table of Outpatient Stays for 2014 */
DATA WORK.OutpatientStays;
	SET	RIF2014.OUTPATIENT_CLAIMS_01
  		RIF2014.OUTPATIENT_CLAIMS_02
		RIF2014.OUTPATIENT_CLAIMS_03
		RIF2014.OUTPATIENT_CLAIMS_04
		RIF2014.OUTPATIENT_CLAIMS_05
		RIF2014.OUTPATIENT_CLAIMS_06
		RIF2014.OUTPATIENT_CLAIMS_07
		RIF2014.OUTPATIENT_CLAIMS_08
		RIF2014.OUTPATIENT_CLAIMS_09
		RIF2014.OUTPATIENT_CLAIMS_10
		RIF2014.OUTPATIENT_CLAIMS_11
		RIF2014.OUTPATIENT_CLAIMS_12;
RUN;

DATA WORK.OutpatientHCPCS;
	SET	RIF2014.OUTPATIENT_REVENUE_01
  		RIF2014.OUTPATIENT_REVENUE_02
		RIF2014.OUTPATIENT_REVENUE_03
		RIF2014.OUTPATIENT_REVENUE_04
		RIF2014.OUTPATIENT_REVENUE_05
		RIF2014.OUTPATIENT_REVENUE_06
		RIF2014.OUTPATIENT_REVENUE_07
		RIF2014.OUTPATIENT_REVENUE_08
		RIF2014.OUTPATIENT_REVENUE_09
		RIF2014.OUTPATIENT_REVENUE_10
		RIF2014.OUTPATIENT_REVENUE_11
		RIF2014.OUTPATIENT_REVENUE_12;
RUN;

PROC SQL;
	DROP TABLE WORK.HCPCS;
	CREATE TABLE WORK.HCPCS AS
	SELECT DISTINCT BENE_ID, CLM_ID, HCPCS_CD
	FROM WORK.OutpatientHCPCS
	WHERE HCPCS_CD IS NOT NULL;
QUIT;

PROC SQL;
	DROP TABLE IMC969SL.HCPCS_OP_2014;
	CREATE TABLE IMC969SL.HCPCS_OP_2014 AS
	SELECT HCPCS_CD, Count(CLM_ID) AS OP_Count, 2014 AS Year
	FROM WORK.HCPCS
	GROUP BY HCPCS_CD;
QUIT;

PROC TRANSPOSE data=WORK.HCPCS out=WORK.ReshapeHCPCS
	(drop=_NAME_ _LABEL_) prefix=Code;
	var HCPCS_CD;
	by BENE_ID CLM_ID;
RUN;


PROC SQL;
	DROP TABLE IMC969SL.OutpatientStays_2014;
	CREATE TABLE IMC969SL.OutpatientStays_2014 AS
	SELECT a.BENE_ID, a.CLM_ID, a.CLM_FROM_DT, a.CLM_THRU_DT, a.PRVDR_NUM, 
		a.ORG_NPI_NUM, a.OP_PHYSN_NPI,
		a.CLM_PMT_AMT, a.CLM_TOT_CHRG_AMT, 
		a.PRNCPAL_DGNS_CD, a.ICD_DGNS_CD1, a.ICD_DGNS_CD2, a.ICD_DGNS_CD3, a.ICD_DGNS_CD4, a.ICD_DGNS_CD5, 
		a.ICD_DGNS_CD6, a.ICD_DGNS_CD7, a.ICD_DGNS_CD8, a.ICD_DGNS_CD9, a.ICD_DGNS_CD10,
		a.ICD_PRCDR_CD1, a.ICD_PRCDR_CD2, b.CODE1, b.CODE2, b.CODE3, b.CODE4, b.CODE5, b.CODE6, 
		b.CODE7, b.CODE8, b.CODE9, b.CODE10 
	FROM WORK.OutpatientStays AS a
	LEFT JOIN WORK.ReshapeHCPCS AS b
		ON a.CLM_ID=b.CLM_ID AND a.BENE_ID=b.BENE_ID;
QUIT;


/* Create Table of Outpatient Stays for 2015 */
DATA WORK.OutpatientStays;
	SET	RIF2015.OUTPATIENT_CLAIMS_01
  		RIF2015.OUTPATIENT_CLAIMS_02
		RIF2015.OUTPATIENT_CLAIMS_03
		RIF2015.OUTPATIENT_CLAIMS_04
		RIF2015.OUTPATIENT_CLAIMS_05
		RIF2015.OUTPATIENT_CLAIMS_06
		RIF2015.OUTPATIENT_CLAIMS_07
		RIF2015.OUTPATIENT_CLAIMS_08
		RIF2015.OUTPATIENT_CLAIMS_09
		RIF2015.OUTPATIENT_CLAIMS_10
		RIF2015.OUTPATIENT_CLAIMS_11
		RIF2015.OUTPATIENT_CLAIMS_12;
RUN;

DATA WORK.OutpatientHCPCS;
	SET	RIF2015.OUTPATIENT_REVENUE_01
  		RIF2015.OUTPATIENT_REVENUE_02
		RIF2015.OUTPATIENT_REVENUE_03
		RIF2015.OUTPATIENT_REVENUE_04
		RIF2015.OUTPATIENT_REVENUE_05
		RIF2015.OUTPATIENT_REVENUE_06
		RIF2015.OUTPATIENT_REVENUE_07
		RIF2015.OUTPATIENT_REVENUE_08
		RIF2015.OUTPATIENT_REVENUE_09
		RIF2015.OUTPATIENT_REVENUE_10
		RIF2015.OUTPATIENT_REVENUE_11
		RIF2015.OUTPATIENT_REVENUE_12;
RUN;

PROC SQL;
	DROP TABLE WORK.HCPCS;
	CREATE TABLE WORK.HCPCS AS
	SELECT DISTINCT BENE_ID, CLM_ID, HCPCS_CD
	FROM WORK.OutpatientHCPCS
	WHERE HCPCS_CD IS NOT NULL;
QUIT;

PROC SQL;
	DROP TABLE IMC969SL.HCPCS_OP_2015;
	CREATE TABLE IMC969SL.HCPCS_OP_2015 AS
	SELECT HCPCS_CD, Count(CLM_ID) AS OP_Count, 2015 AS Year
	FROM WORK.HCPCS
	GROUP BY HCPCS_CD;
QUIT;

PROC TRANSPOSE data=WORK.HCPCS out=WORK.ReshapeHCPCS
	(drop=_NAME_ _LABEL_) prefix=Code;
	var HCPCS_CD;
	by BENE_ID CLM_ID;
RUN;


PROC SQL;
	DROP TABLE IMC969SL.OutpatientStays_2015;
	CREATE TABLE IMC969SL.OutpatientStays_2015 AS
	SELECT a.BENE_ID, a.CLM_ID, a.CLM_FROM_DT, a.CLM_THRU_DT, a.PRVDR_NUM, 
		a.ORG_NPI_NUM, a.OP_PHYSN_NPI,
		a.CLM_PMT_AMT, a.CLM_TOT_CHRG_AMT, 
		a.PRNCPAL_DGNS_CD, a.ICD_DGNS_CD1, a.ICD_DGNS_CD2, a.ICD_DGNS_CD3, a.ICD_DGNS_CD4, a.ICD_DGNS_CD5, 
		a.ICD_DGNS_CD6, a.ICD_DGNS_CD7, a.ICD_DGNS_CD8, a.ICD_DGNS_CD9, a.ICD_DGNS_CD10,
		a.ICD_PRCDR_CD1, a.ICD_PRCDR_CD2, b.CODE1, b.CODE2, b.CODE3, b.CODE4, b.CODE5, b.CODE6, 
		b.CODE7, b.CODE8, b.CODE9, b.CODE10 
	FROM WORK.OutpatientStays AS a
	LEFT JOIN WORK.ReshapeHCPCS AS b
		ON a.CLM_ID=b.CLM_ID AND a.BENE_ID=b.BENE_ID;
QUIT;




/* Calculate total OP counts by physician */

%LET year_data=2015;
PROC SQL;
	DROP TABLE WORK.Physicians;
	CREATE TABLE WORK.Physicians AS
	SELECT DISTINCT OP_PHYSN_NPI as Physician_NPI
		FROM IMC969SL.INPATIENTSTAYS_&year_data 
		WHERE OP_PHYSN_NPI IS NOT NULL;
QUIT;

PROC SQL;
	DROP TABLE WORK.Outpatient_Small;
	CREATE TABLE WORK.Outpatient_Small AS
	SELECT OP_PHYSN_NPI AS Physician_ID, BENE_ID, count(CLM_ID) AS OP_Claims, sum(CLM_TOT_CHRG_AMT) as OP_Charge, 
		count(distinct ORG_NPI_NUM) AS Hosp_Count, sum(CLM_PMT_AMT) AS OP_Pay
	FROM IMC969SL.OutpatientStays_&year_data
	WHERE OP_PHYSN_NPI IS NOT NULL
	GROUP BY OP_PHYSN_NPI, BENE_ID;
QUIT;

PROC SQL;
	DROP TABLE IMC969SL.OP_Counts_&year_data;
	CREATE TABLE IMC969SL.OP_Counts_&year_data AS
	SELECT Physician_ID AS Physician_NPI, BENE_ID, OP_Claims, OP_Charge, OP_Pay, Hosp_Count, &year_data AS Year
		FROM WORK.Outpatient_Small AS a
		INNER JOIN WORK.Physicians AS b
		ON a.Physician_ID=b.Physician_NPI;
QUIT;




/* Calculate total HCPCS counts by physician */


%LET year_data=2008;
PROC SQL;
	DROP TABLE WORK.HCPCS_OP_Physician;
	CREATE TABLE WORK.HCPCS_OP_Physician AS
	SELECT OP_PHYSN_NPI, ORG_NPI_NUM, CODE1, CODE2, CODE3, CODE4, CODE5, CODE6, 
		CODE7, CODE8, CODE9, CODE10
	FROM IMC969SL.OutpatientStays_&year_data
	WHERE OP_PHYSN_NPI IS NOT NULL
		AND ORG_NPI_NUM IS NOT NULL
	ORDER BY OP_PHYSN_NPI, ORG_NPI_NUM;
QUIT;

data WORK.HCPCS_OP_Physician;
	set WORK.HCPCS_OP_Physician;
	Phy_Hosp + 1;
run;

PROC TRANSPOSE data=WORK.HCPCS_OP_Physician out=WORK.ReshapeHCPCS
	(rename=(Col1=Value)) name=Code;
	by Phy_Hosp;
	var Code1 Code2 Code3 Code4 Code5 Code6 Code7 Code8 Code9 Code10;
RUN;

data WORK.ReshapeHCPCS;
merge WORK.ReshapeHCPCS
	WORK.HCPCS_OP_Physician(keep=Phy_Hosp OP_PHYSN_NPI ORG_NPI_NUM);
	by Phy_Hosp;
run;

PROC SQL;
	DROP TABLE IMC969SL.HCPCS_OP_Physician_&year_data;
	CREATE TABLE IMC969SL.HCPCS_OP_Physician_&year_data AS
	SELECT DISTINCT OP_PHYSN_NPI as Physician_NPI, ORG_NPI_NUM, Value, count(Value) as Count
		FROM WORK.ReshapeHCPCS
		WHERE Value IS NOT NULL
		GROUP BY OP_PHYSN_NPI, ORG_NPI_NUM, Value;
QUIT;
